### ISSUE TITLE
[Bug]: Upgrading to v4 drops existing OIDC key and create new ones

### ISSUE THREAD

**Issue by yann-soubeyrand** [zitadel/zitadel#10519]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v4.0.2

### Database

PostgreSQL

### Database Version

17

### Describe the problem caused by this bug

When upgrading a v3 instance to v4, the keys used to sign OIDC tokens in v3 are lost and new keys are created. Therefore, existing tokens cannot be verified any more.

### To reproduce

- Launch a ZITADEL v3.3.6 instance:
  ```
  curl -O https://raw.githubusercontent.com/zitadel/zitadel/main/docs/docs/self-hosting/deploy/docker-compose.yaml
  sed -ri '/^\s*login:/,/^\s*$/d' docker-compose.yaml
  sed -ri '/^\s*image: ghcr.io\/zitadel\/zitadel:/s/[^:]+$/v3.3.6/' docker-compose.yaml
  podman compose up -d
  ```
- Take note of the keys:
  http://localhost:8080/oauth/v2/keys
- Update the ZITADEL instance to v4.0.2:
  ```
  podman compose stop
  sed -ri '/^\s*image: ghcr.io\/zitadel\/zitadel:/s/[^:]+$/v4.0.2/' docker-compose.yaml
  podman compose up -d
  ```
- See that the previous key is not there any more:
  http://localhost:8080/oauth/v2/keys

### Expected behavior

The existing keys in v3 should be conserved (even if deactivated).

**Comment by elinashoko** [comment]
Hello, sorry for the troubles @yann-soubeyrand  - we deployed a fix for this: https://github.com/zitadel/zitadel/pull/10105

**Comment by yann-soubeyrand** [comment]
@elinashoko I may be wrong, but I think this issue is not fixed. If I understand correctly, in v3, until the web key feature is enabled, tokens are signed with “legacy” keys. During upgrade to v4, web key feature is enabled (and cannot be disabled) and “legacy” keys are dropped. Therefore, tokens issued before the upgrade are not valid any more. Still if I understand correctly, backporting the web key generation setup step is not useful, because it’s only necessary during an instance first start with web key feature enabled (which cannot happen in v3?). For the upgrade, I think the doc has to indicate that web key feature should be enabled prior to deploying v4 (and I guess people have to wait for all the tokens issued using “legacy” keys to expire before upgrading). And maybe the latest v3 versions could enforce enabling web key feature. Did I miss something?

**Comment by yann-soubeyrand** [comment]
@elinashoko any news?
