### ISSUE TITLE
[Bug]: Domain Discovery doesn't work

### ISSUE THREAD

**Issue by alishchytovych** [zitadel/zitadel#10662]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v4.1.2

### Database

PostgreSQL

### Database Version

CNPG 1.26.1

### Describe the problem caused by this bug

Fresh instance of Zitadel v4.1.2. Few organizations added, each has:
- External Login allowed - yes
- Domain Discovery allowed
- IdP added (automatic creation, update, account creation, linking - yes)
- Verified domains - added (verified), one of them - "test.com"
- Main org (set default) has project (other orgs granted an access) and app registered (web app, PKCE etc.)
- Default settings - Domain Discovery allowed - yes

### To reproduce

Opening /oauth/v2/authorize?client_id=336843055229370947&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1&scope=openid%20profile%20email - show Login UI (v2) form of Main org. 

If I enter loginname "test@test.com" (this is a new user, not created in Zitadel) and press "Continue" - it shows "User not found in the system". 

### Screenshots

<img width="463" height="624" alt="Image" src="https://github.com/user-attachments/assets/f08ae5f0-ef05-49fa-86f4-8d451266b23f" />

<img width="681" height="426" alt="Image" src="https://github.com/user-attachments/assets/83aa2911-6fdc-464f-b89c-aef2c8748bf9" />

<img width="453" height="717" alt="Image" src="https://github.com/user-attachments/assets/c595c7c2-c08a-4838-a920-a70318caf8d4" />

<img width="1371" height="311" alt="Image" src="https://github.com/user-attachments/assets/0f6513c9-68d0-459b-9e1c-021d2f5269f7" />

### Expected behavior

Expected behaviour - via domain discovery find organization with "test.com" and forward to IdP configured to continue with auth and subsequent registration.

### Operating System

OKD 4.15 or Docker - behaviour is the same

**Comment by dataviruset** [comment]
I wanted to try out domain discovery as well and I can confirm I have the same issue with very a similar config as you.

**Comment by nuvqe** [comment]
Guys, any updates?

**Comment by alishchytovych** [comment]
Hi @elinashoko @peintnermax,
Do we have any ETA? Is it a bug or configuration issue?

**Comment by peintnermax** [comment]
this was fixed with #10729

**Comment by dataviruset** [comment]
> this was fixed with [#10729](https://github.com/zitadel/zitadel/pull/10729)

I tried upgrading to Zitadel 4.3.1 but the issue still persists, it's reproducible here on my end if I follow the steps described in the first post and https://zitadel.com/docs/guides/solution-scenarios/domain-discovery

Basically have a default organization foo@example.com with domain discovery enabled, then enable an external IdP in another organization with domain discovery enabled and a verified domain secondorg.com. I didn't require an actual verification with ACME. Then try to log in with the loginname foo@secondorg.com on the default organization login page and it will just say "User not found in the system" without logging in with the external IdP configured on the other organization.

**Comment by micael-pn** [comment]
Hello,
Any news regarding this issue ? I can't get Domain Discovery working, both with Login V1 and Login V2 : 

- I have enabled "Username and Password allowed" and "Domain Discovery allowed" on Default Settings

<img width="1012" height="919" alt="Image" src="https://github.com/user-attachments/assets/b03acc24-1bfe-41c0-bdaa-e96d8feb0961" />

- I have enabled "Username and Password allowed", "External Login allowed" and "Domain Discovery allowed" for the target Organization

<img width="1098" height="898" alt="Image" src="https://github.com/user-attachments/assets/2d08fbac-4e06-472e-8e75-f516557e5c25" />

- I added the domain as Verified Domain for the target Organization

<img width="1326" height="671" alt="Image" src="https://github.com/user-attachments/assets/f62a2397-c90e-4f6b-967b-048ec05dcb31" />

- I added an External Identity Provider for the target Organization

<img width="1368" height="530" alt="Image" src="https://github.com/user-attachments/assets/95ebfe6e-de53-4e31-9025-3e27c01038fb" />


Unfortunately, when I try to login with a user using a Verified Domain, I am always redirected to Username and Password instead of being redirected to External Identity Provider

https://github.com/user-attachments/assets/be4eccec-8f1c-4c8b-89c0-79b92862fce7


I am posting here because Ask AI on Zitadel's documentation points this issue as potential cause of the problem

Thank you

**Comment by elinashoko** [comment]
Heya @dataviruset @micael-pn thank you for reporting and sorry for the troubles! I've reopened this issue and we will investigate.

**Comment by elinashoko** [comment]
Fix currently in review!

**Comment by micael-pn** [comment]
Hello @elinashoko @peintnermax ,

We are still experiencing the issue presented [in this comment](https://github.com/zitadel/zitadel/issues/10662#issuecomment-3415404969) with the last release v4.5.0 with both Login V1 and Login V2 : even if the domain example.com is set as Verified Domain for an Organization, the user is not redirected to the configured External IdPs when both "username and password allowed" and "External login allowed" enabled

Am I missing something ?

**Comment by linwalth** [comment]
We also experience this issue in v2. v1 works though.

**Comment by peintnermax** [comment]
> We also experience this issue in v2. v1 works though.

could you please retry version [4.5.0](https://github.com/zitadel/zitadel/compare/v4.4.0...v4.5.0) and let us know if your problem got resolved? Thank you!

**Comment by jnull** [comment]
Tried it with zitadel v2.5.0 and zitadel-login v2.5.0. With the exact same result as OP. Unfortunately the bug is not resolved.

**Comment by micael-pn** [comment]
> > We also experience this issue in v2. v1 works though.
> 
> could you please retry version [4.5.0](https://github.com/zitadel/zitadel/compare/v4.4.0...v4.5.0) and let us know if your problem got resolved? Thank you!

Hi @peintnermax 

Unfortunately, Domain Discovery doesn't work with either Login V1 and V2 for us : 

We have a user jackson@example.com in Test SAML Organization
<img width="1920" height="962" alt="Image" src="https://github.com/user-attachments/assets/13c79bb0-8cf9-43a2-aacd-8d719db32b6b" />

We have setup two External IdPs for that Org
<img width="1920" height="960" alt="Image" src="https://github.com/user-attachments/assets/10ef56f1-affb-496d-8a6a-c8a2edc00d14" />

Domain example.com is set as Verified Domain for that Org
<img width="1920" height="961" alt="Image" src="https://github.com/user-attachments/assets/921225a8-7eb0-42d1-b636-00ecaa7b286e" />

Username/password, External Login and Domain Discovery and are enabled for that Org **and in the Default settings** 
<img width="1920" height="961" alt="Image" src="https://github.com/user-attachments/assets/edc28df7-d645-4ec4-9d30-b59345e11e0a" />
<img width="1920" height="959" alt="Image" src="https://github.com/user-attachments/assets/ca1112bf-d6ca-4a5b-a6a8-9ec057a4a681" />

When trying to login with jackson@example.com with Login V1, the password form is presented. When we hit the back button, both external IdPs are presented
<img width="1710" height="984" alt="Image" src="https://github.com/user-attachments/assets/2b6fe1ee-8653-45dd-a448-eb374b026d39" />
<img width="1710" height="985" alt="Image" src="https://github.com/user-attachments/assets/7aa273de-16a1-464b-871d-03016bded0f7" />

When trying to login with jackson@example.com with Login V2, the password form is also presented. When we hit the back button, no external IdP is shown
<img width="1710" height="984" alt="Image" src="https://github.com/user-attachments/assets/262151dd-054d-4833-a638-aabb1f4ee514" />
<img width="1920" height="962" alt="Image" src="https://github.com/user-attachments/assets/47862131-a796-43e5-8fc7-2fcf2cef676d" />

Are we missing something ? Can we help ?

Thanks

**Comment by peintnermax** [comment]
> > > We also experience this issue in v2. v1 works though.
> > 
> > 
> > could you please retry version [4.5.0](https://github.com/zitadel/zitadel/compare/v4.4.0...v4.5.0) and let us know if your problem got resolved? Thank you!
> 
> Hi [@peintnermax](https://github.com/peintnermax)
> 
> Unfortunately, Domain Discovery doesn't work with either Login V1 and V2 for us :
> 
> We have a user [jackson@example.com](mailto:jackson@example.com) in Test SAML Organization <img alt="Image" width="1920" height="962" src="https://private-user-images.githubusercontent.com/56550952/506441484-13c79bb0-8cf9-43a2-aacd-8d719db32b6b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDE0ODQtMTNjNzliYjAtOGNmOS00M2EyLWFhY2QtOGQ3MTlkYjMyYjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDcwOTFmY2EwYjdhNjE1OWE2NGFlODFjZDlkNGM1N2E3YTU3MjljYTRiYTYzYzI3ZjVlZGYyYzBhNTcwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yf1oE1BDQwUKJ5l-auYlOOY4NzZgJ202Y5baK-ijLxs">
> 
> We have setup two External IdPs for that Org <img alt="Image" width="1920" height="960" src="https://private-user-images.githubusercontent.com/56550952/506441641-10ef56f1-affb-496d-8a6a-c8a2edc00d14.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDE2NDEtMTBlZjU2ZjEtYWZmYi00OTZkLThhNmEtYzhhMmVkYzAwZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNzU0ZTRhYmM3ZjdmN2NhZDE1MmFkYjQzNTE4ZWZjMDkzNjJiNDIxZDYxNzAzNjJjNzdlOWZjYmU2ZjJkZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q8KfzPXNiBIQae29oRtC4VCITuwc_4dX7TJtxTomb94">
> 
> Domain example.com is set as Verified Domain for that Org <img alt="Image" width="1920" height="961" src="https://private-user-images.githubusercontent.com/56550952/506441758-921225a8-7eb0-42d1-b636-00ecaa7b286e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDE3NTgtOTIxMjI1YTgtN2ViMC00MmQxLWI2MzYtMDBlY2FhN2IyODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyM2UwYTQ0ZWQ1MTAzNmUyOGNmNmNmZTIxY2JmZmZlYzc5OGQzODI0NzAxMjI3ZDdhNWRkOTY3Yzc0NWViYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MUj5y7A-H7tOQVNB5fpGWxIFfCS9u2G5s_GSwk53AAQ">
> 
> Username/password, External Login and Domain Discovery and are enabled for that Org **and in the Default settings** <img alt="Image" width="1920" height="961" src="https://private-user-images.githubusercontent.com/56550952/506441951-edc28df7-d645-4ec4-9d30-b59345e11e0a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDE5NTEtZWRjMjhkZjctZDY0NS00ZWM0LTlkMzAtYjU5MzQ1ZTExZTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTQ2ZmE5YTYxYzNlMTQ0NjI0YmM4YWQ5MjMwNGQ1YmUzN2FjMGI1NzY2MGFjNzEzODFmODVhMWRiOWRlZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PKkqetqd0Cl4FWBHBN3LyN_N3cMTY2kahioJ_0DQYN4"> <img alt="Image" width="1920" height="959" src="https://private-user-images.githubusercontent.com/56550952/506442580-ca1112bf-d6ca-4a5b-a6a8-9ec057a4a681.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDI1ODAtY2ExMTEyYmYtZDZjYS00YTViLWE2YTgtOWVjMDU3YTRhNjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZjA5MzkzMjM4YjJiZmVhY2MzZTE5Nzg3ODdkNTBkZDNiYmJjZGE4OTYyZThiMzBlMmM4OTNlM2JkNDgwMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TwIowx-rvG2ZH2vg4Xga-FpcIG8C7DXEvoh0q_ZQJt4">
> 
> When trying to login with [jackson@example.com](mailto:jackson@example.com) with Login V1, the password form is presented. When we hit the back button, both external IdPs are presented <img alt="Image" width="1710" height="984" src="https://private-user-images.githubusercontent.com/56550952/506443024-2b6fe1ee-8653-45dd-a448-eb374b026d39.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDMwMjQtMmI2ZmUxZWUtODY1My00NWRkLWE0NDgtZWIzNzRiMDI2ZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZjZmYjc1MTYxOTllZDc0OTY1YjZmYmQ0ODE0MzJlNWJlYzczNWJhZWRjNTg4MDkyMzM5N2NhN2NmMDdjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O09ERaV-kuthE7JLnn6k7l87TuQzNOEHF4DJhctMMlo"> <img alt="Image" width="1710" height="985" src="https://private-user-images.githubusercontent.com/56550952/506443061-7aa273de-16a1-464b-871d-03016bded0f7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDMwNjEtN2FhMjczZGUtMTZhMS00NjRiLTg3MWQtMDMwMTZiZGVkMGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NDUzNzVmMDRlMzgzNDkzN2RmYWU0NGMwYzRjZThiNjAxYjExNTNjNmMzMGJhYmEwMmVmOWZjZTE4YWY3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XdIR8k-nzpxX1oaDLv6RG_fhb-U1ohRDzV1N82ijF4Y">
> 
> When trying to login with [jackson@example.com](mailto:jackson@example.com) with Login V2, the password form is also presented. When we hit the back button, no external IdP is shown <img alt="Image" width="1710" height="984" src="https://private-user-images.githubusercontent.com/56550952/506443209-262151dd-054d-4833-a638-aabb1f4ee514.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDMyMDktMjYyMTUxZGQtMDU0ZC00ODMzLWE2MzgtYWFiYjFmNGVlNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YzEyY2JhYzRiZDUwNDgyODFiZjM0MDE1ZDc3MmE4ZTU5NTQ3ZDM4ZjBlNTdiZGQzMTEzNTUxOWFjZDNhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4gIGeK-eRD4W2xXDPuSt63Rip52OyeLMl0VmM5MMQUQ"> <img alt="Image" width="1920" height="962" src="https://private-user-images.githubusercontent.com/56550952/506443240-47862131-a796-43e5-8fc7-2fcf2cef676d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NDMzODgsIm5iZiI6MTc2MTY0MzA4OCwicGF0aCI6Ii81NjU1MDk1Mi81MDY0NDMyNDAtNDc4NjIxMzEtYTc5Ni00M2U1LThmYzctMmZjZjJjZWY2NzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA5MTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiODVkNzAyYzNlNDE0Njc2OTI3Y2RmMDM0OWFhMWFiNGZkYWU3NTUyNThlMjBhMTcwNWUxODZjOGIxMDdiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BXn9DuzNTV10-yQvC5eGaRw9ao3H43OK4jdpNy7s9aY">
> 
> Are we missing something ? Can we help ?
> 
> Thanks

If you are using cloud you may have to wait until we release 4.5.0. this issue mentions self hosted environments which could hop on 4.5.0 to retest the scenario.

**Comment by micael-pn** [comment]
> If you are using cloud you may have to wait until we release 4.5.0. this issue mentions self hosted environments which could hop on 4.5.0 to retest the scenario.

I confirm that we use Self Hosted version of Zitadel with v4.5.0 for both Zitadel and Login. This is why I am confused and wondering if we are missing something 🫤

**Comment by peintnermax** [comment]
@micael-pn I see a that you have mentioned "navigating back". Does this mean that org discovery is working fine on the first page of the login v2 (password page) but that the state of the org is not persisted when navigating back? would you be able to send us a HAR file of the whole flow to better understand how you end up on those pages?  We'd appreciate if you could send it over to support@zitadel.com and mention this issue as a reference. Thank you!

**Comment by jnull** [comment]
@peintnermax I'd like to expand on my test: I set up Zitadel v4.5.0 with zitadel-login v4.5.0 locally, enabled and set login v2 base uri, created an Org with `test.local` set as verified and primary domain. Enabled `domain discovery allowed` and `external login allowed` and added a generic oidc idp. Then I tried login in with a test user `test-user@test.local` and still received `User not found in the system` as error message instead of being forwarded to the external IDP

**Comment by micael-pn** [comment]
> [@micael-pn](https://github.com/micael-pn) I see a that you have mentioned "navigating back". Does this mean that org discovery is working fine on the first page of the login v2 (password page) but that the state of the org is not persisted when navigating back? would you be able to send us a HAR file of the whole flow to better understand how you end up on those pages? We'd appreciate if you could send it over to [support@zitadel.com](mailto:support@zitadel.com) and mention this issue as a reference. Thank you!

Request information has been sent 👍

**Comment by micael-pn** [comment]
Hi @peintnermax ,
Do you need more information ? I see that there is a PR that seams related to this issue (#10996). Is it related ? Can you also confirm that the fix will be also available for Login V1 ?
Thanks

**Comment by peintnermax** [comment]
> Hi [@peintnermax](https://github.com/peintnermax) , Do you need more information ? I see that there is a PR that seams related to this issue ([#10996](https://github.com/zitadel/zitadel/pull/10996)). Is it related ? Can you also confirm that the fix will be also available for Login V1 ? Thanks

Hi Micaël,

Exactly. This should resolve your issue and be merged soon. Your issue was related to the /loginname page not correctly resolving the organization domain. The linked PR should fix that. 
This domain discovery issue should not affect the login v1 though. Did you expericence issues using the old v1 login too?

**Comment by micael-pn** [comment]
@peintnermax Yes, I confirm that the issue also appears in Login V1 as mentioned [in this comment](https://github.com/zitadel/zitadel/issues/10662#issuecomment-3455200525) and on the debug information shared by email.

Let me know if you need more information 👍

**Comment by micael-pn** [comment]
Hello @peintnermax ,
I tested the last build v4.6.3 with both Login V1 and V2. I am still experiencing the same issue.
Is there something more that I can help with to fix the problem ?
Thanks

**Comment by micael-pn** [comment]
Sorry about the last comment. I though that #11026 that was merged in v4.6.3 was related to this issue.
Looking forward for a fix for both Login V1 and Login V2 !

**Comment by micael-pn** [comment]
Hi @peintnermax ,
Do you have any ETA to resolve that issue for both Login V1 and V2 ?
Thanks

**Comment by peintnermax** [comment]
@micael-pn we've just merged https://github.com/zitadel/zitadel/pull/10996 that should fix the org discovery as part of the /loginname page. That is the issue you most likely run into when navigating back. 
We'd appreciate if you could retest your specific flow with our next login v2 version and let us know if this resolves your issue.

**Comment by micael-pn** [comment]
@peintnermax Thanks. Is the fix available in a tagged version ?

> We'd appreciate if you could retest your specific flow with our next login v2 version and let us know if this resolves your issue.

I can test on Login V2 but we are still using Login V1 since the former still has important issues that prevents us to make the switch. Does the fix also apply for V1 ?

Thanks

**Comment by dataviruset** [comment]
Some tests we did with Zitadel 4.7.0 suggests that the issue has been resolved. The error messages were a bit confusing when accounts hadn't been created yet but after enabling registration ("User Registration allowed" in the settings of the organization), it seems to redirect to the 3rd party identity provider we configured.

We had some issues with uppercase/lowercase handling, it wouldn't detect the already existing user account if the email address was registered with a lowercase email address but the user put in an initial uppercase letter during login (common because the input method defaults to initial uppercase on mobile phone keyboards and it seems that the Zitadel input field isn't treated as an email field?)

The behavior we observed was that we got "User not found" when putting in the email address with an initial uppercase letter. When putting in the email address without the initial uppercase letter or a non-existing email address, it would redirect to the 3rd party identity provider as expected.

Opened a separate issue: https://github.com/zitadel/zitadel/issues/11124

**Comment by micael-pn** [comment]
Hello @peintnermax ,

We tested the release v4.7.0. We are still experiencing the issue with Domain Discovery not working **with both Login V1 and Login V2**

Exactly the same behaviour [as this comment](https://github.com/zitadel/zitadel/issues/10662#issuecomment-3455200525).

Can someone help ? Are we missing the purpose of this feature ? We would like to achieve the following scenario (already shared on Discord) : 

For an Organization : 
- example.com is verified in this Organization.
- an External Identity Provider (e.g., Google/Azure) is configured.
- two users are created within this organization : jackson@example.com (matches the verified domain) and jackson@example.org (does not match the verified domain).

When users attempt to log in, we need the flow to branch based on their email domain:

- For jackson@example.com, Zitadel should automatically redirect the user to the External IdP.
- For jackson@example.org, Zitadel should display the standard Zitadel login form (Username/Password).

Thank you

**Comment by gwku** [comment]
Same problem for me. Additional information:
- using scope `urn:zitadel:iam:org:domain:primary:domain.com` results in query parameter `&suffix=domain.com` when no account is logged in yet (and if you directly login using this way, it works correctly). However, if the profile chooser already contains some items, and I click 'use another account', this suffix is not propagated. So I get the error: `User not found in system`.
- using scope `urn:zitadel:iam:org:id:{id}` results in no domain suffix query parameter, which also will produce the `User not found in system` error
- When I enable the setting in organization branding settings for hiding the suffix, the login page will still show the suffix with scope `urn:zitadel:iam:org:domain:primary:domain.com` (the id scope never shows the domain suffix)

Hope this helps! If you have any questions, I'm glad to provide more information.

Edit: what I described above is applicable for version 4.7.0 (latest at this time).

**Comment by micael-pn** [comment]
Hello,
Do you have some news to share regarding this issue ?
Thank you

**Comment by elinashoko** [comment]
Heya @micael-pn @gwku we're going to investigate again and get back to you, thank you for the patience.

**Comment by micael-pn** [comment]
Hi @livio-a,
I see that you self-assigned this issue. Do you have any update regarding a fix ?

Can you also confirm that the behaviour described [in this comment](https://github.com/zitadel/zitadel/issues/10662#issuecomment-3606372633) is how Domain Discovery should work ? Can you also confirm that the bug is going to be fixed both on Login V1 and Login V2 since the later is still having other issues ?

Thank you for your help

**Comment by livio-a** [comment]
Hey @micael-pn, @gwku  and @alishchytovych 

I'm getting myself an overview of the current state and this issue since there are different cases and expectations mentioned.

The general concept is the following:
- Zitadel resp. its login works in a identity first way, meaning whenever a user exists within the given scope (more to that below) the user will be given the possible / allowed auth method(s).
- If a user doesn't exist / can't be found, (among other options, it falls back to domain discovery, if configured.
- For domain discovery we'll use the suffix from the entered input (e.g. example.com / example.org) to check for an organization with the corresponding verified domain. (Note that an organization can have multiple verified domains). In case we find an organization and domain discovery is allowed based on its policy, we'll use the policy to provide the possible registration options. This could be one or multiple IdPs and / or local registration. If the only possibility is a single IdP, the user will automatically be redirected to that.
- Regarding scope for the login: by default all users within the instance will be allowed to login. There are multiple scopes to restrict that to a single organization.

@micael-pn based on that concept if there are local and federated users in the same organization, you could let the latter be automatically created / federated through the domain discovery and the local one either though the API (as I guess you did already?). I don't know your use case and how the process looks like to onboard them, but maybe using the invite flow, where the user can decide which auth method (password / passkey or the IdP) might be an option.

I'll try to clarify what the state of this concept is in login V2 and if there are still bugs or if these affect related topics like the one from @dataviruset .

**Comment by micael-pn** [comment]
Hello @livio-a ,

Thank you for the quick reply. Let me share de scenarios already discussed with @rajatcing [here](https://discord.com/channels/927474939156643850/1412462329525964841/1432645337507692638)

**Scenario #1**

1. We have an existing Organization with a user james@gmail.com and "Username and Password" login enabled
2. We invite a new user jackson@example.com to that Organization through the API
3. A few weeks later, we enable an external IdP, set example.com as Verified domain and enable both "Domain discovery" and "External Login" while keeping "Username and Password" login enabled for that Organization

=> Here, we expect james@gmail.com to be prompted with username/password form and jackson@example.com to be redirected to the external IdP. Is it correct ? If so, can you please share the exact steps to achieve that ?

**Scenario #2**

1. We have an existing Organization with a user michael@university.com, the domain "university.com" set as Verified Domain, an External IdP configured and "Domain discovery", "External Login" and "Username and Password" login enabled
3. We invite a new user david@university.com to that Organization through the API
4. We invite a new user william@gmail.com to that Organization  through the API

=> Here, we expect michael@university.com and david@university.com to be redirected to the external IdP while william@gmail.com logs in with the username/password form. Is it correct ? If so, can you please share the exact steps to achieve that ?

Can you check if both scenarios are achievable ?

> based on that concept if there are local and federated users in the same organization, you could let the latter be automatically created / federated through the domain discovery and the local one either though the API (as I guess you did already?). I don't know your use case and how the process looks like to onboard them, but maybe using the invite flow, where the user can decide which auth method (password / passkey or the IdP) might be an option.

The use case is the following : 

- Our users are invited using the API trough our Saas web software. In detail : we use `v2/users/new`using the email address of the new user and `v2/users/:userId/invite_code` to send him an invitation.
- The new user receives the invitation from Zitadel. He sets his password using the invite link received by email

Can you confirm that the scenarios presented above would work with the use case ?

Thanks

**Comment by micael-pn** [comment]
Hi,
Any news ?
Thanks

**Comment by micael-pn** [comment]
Hello @livio-a ,
Any update on this ?
I remain available for further information or testing.
Thank you

**Comment by lligirlburg-wq** [comment]
Ok

**Comment by lligirlburg-wq** [comment]
Hello

**Comment by lligirlburg-wq** [comment]
Hello> Ok

**Comment by jnull** [comment]
just as a small update. I tested again with the latest release v4.10.1 and login v2 active it seems that domain discovery works but for some reason I don't get forwarded to my remote IDP. Here are the logs:
```
zitadel-login-7b4bf7c6c5-6frjv zitadel-login No users found, will proceed with org discovery
zitadel-login-7b4bf7c6c5-6frjv zitadel-login user not found (0 potential users), checking registration options
zitadel-login-7b4bf7c6c5-6frjv zitadel-login org discovery successful, using org: 360584144138272794
```
In the organization settings the `User registration allowed` is **disabled** because I want only users registered from the remote IDP. Disabling login v2 and it works like a charm.

**Comment by micael-pn** [comment]
We tested 4.11.0 and we are still experiencing the same issue regarding Domain Discovery. Is there any update on this @livio-a ?
Thank you

**Comment by lligirlburg-wq** [comment]
Okay am just a single one of the guys 👦

**Comment by byrnajkhan** [comment]
I just signed up for Zitadel cloud running v4.11.1 to pilot it for our org and I'm hoping I have something misconfigured, otherwise I'm also experiencing this and a bit blown-away. Our goal is B2C for customers while also allowing employees to log in with an external IDP. We have two orgs set up. We have our domain verified on the employee/internal org. The project for the service is in the employee/internal org. The B2C org is project granted to it. If an employee types in their email, they dont get to sign in with our IDP unless the "User Registration allowed" option is checked on our employee/internal org, which is obviously not aceptable. I'm at a bit of a loss.

**Comment by JakobStadlhuber** [comment]
We also facing the same issue

**Comment by mutefiRe** [comment]
**We might have an additional scenario (Login V1, multi-org setup)** and I was not sure if any of the previous comments are facing something similar:

```mermaid
flowchart TD
    A[Default org entry] --> B[Enter email]
    A --> C[Choose OIDC / social]

    B --> D{Match}
    D -->|Enterprise| E[Domain discovery → Entra ID]
    D -->|Root admin| F[Root org → Local login]
    D -->|No match / default| G[Our application OIDC]

    C --> H[OIDC / social login]
```

We use the default org as the main entrypoint (which is the default behaviour anyway I guess):

- Users can either:
  - enter an email/identifier
  - choose an OIDC/social login directly

- After entering an identifier:
  - **enterprise users** → domain discovery → external IdP (e.g. Entra ID)
  - **root admin users** → matches user in root org → local username/password
  - **all other users** → **our own application OIDC**

**Important constraints**
- Local username/password must be **disabled on the default org**
- Local login should **only exist in the root org**
- If fallback behavior is wrong, redirects may create a user-enumeration / probing issue

**Problem**
This currently seems to require username/password to be enabled on the **default org**, which we do not want.

The expected fallback for users that do not match root admin or enterprise domain discovery should be:
**our own application OIDC**, not local username/password.

**Comment by jakob1379** [comment]
ok, so for me it was the absolute bonkers mistake of thinking that this was the "create account", which it is NOT. Notice the small "Register new user"?

<img width="474" height="639" alt="Image" src="https://github.com/user-attachments/assets/05056014-8988-451f-8667-f60f5d09f8d1" />

....

**Comment by redfordwesley320-arch** [comment]
I’ve definitely done that before! The “Register new user” link is pretty
easy to miss. It’s a classic case of assuming what the button is, instead
of actually reading the label. Thanks for pointing that out!

**Comment by byrnajkhan** [comment]
Please upvote my issue / PR. This is not B2C ready with that tiny register new user button. https://github.com/zitadel/zitadel/issues/11845
https://github.com/zitadel/zitadel/pull/11844

**Comment by jnull** [comment]
Can someone clarify this issue? I have the feeling that multiple issues are combined here. The origin was and is that domain discovery for non registered users with external idp auth is not working as the users are declared unknown instead of getting forwarded. Is there any progress or news @livio-a

**Comment by rajatcing** [comment]
cc @elinashoko

**Comment by linwalth** [comment]
Is this still on the radar?

**Comment by elinashoko** [comment]
Hey, everyone! Firstly, thanks for the detailed reports and debugging info. Apologies for the delay, it's taken some time to untangle/ test the different scenarios. 

You are correct, there are several separate problems affecting the domain discovery flow. I've split them into individual bug tickets so they can be tracked and fixed independently:

Login V2 does not redirect to external IdP after successful domain discovery
https://github.com/zitadel/zitadel/issues/12021
Domain discovery does not redirect to external IdP when “User registration allowed” is disabled
https://github.com/zitadel/zitadel/issues/12023
Organization suffix lost during login flow when using “Use another account”
https://github.com/zitadel/zitadel/issues/12024
Email case sensitivity prevents user lookup and domain discovery
https://github.com/zitadel/zitadel/issues/12025

Once these are addressed, the expected behaviour should be that users entering an email address belonging to a verified domain are routed to the authentication methods configured for that org (for example redirecting to the configured IdP).
We'll keep the issues updated as we work through them. Thank you for the patience!

**Comment by micael-pn** [comment]
Hi @elinashoko ,
Thank you for the update.
Can you also confirm that users using different domains belonging to the same organization will be redirected to the appropriate login method as presented [in my previous comment](https://github.com/zitadel/zitadel/issues/10662#issuecomment-3745432258).

For example:

jackson@verified-domain.com and alice@gmail.com belong to the same organization. An external IdP is configured and both login/password and external IdP login methods are enabled for that org.  Domain "verified-domain.com" is verified for that org as well.

Given that setup : 
- When Jackson logs in, he is redirected to the external IdP 
- When Alice logs in, she is redirected to local password method

Is that correct?

Thanks

**Comment by Drowze** [comment]
Is this going to be fixed on v4?

**Comment by elinashoko** [comment]
Hey there, a quick update on the bugs that I created based on this issue/ feedback in the thread: 

https://github.com/zitadel/zitadel/issues/12021 - in progress
https://github.com/zitadel/zitadel/issues/12023- in progress
https://github.com/zitadel/zitadel/issues/12024 - done
https://github.com/zitadel/zitadel/issues/12025 - not started

All will be fixed in V4.

**Comment by micael-pn** [comment]
Hi @elinashoko , thanks for splitting this up.

One thing worth flagging: this issue was originally reported against Login V2, but as the thread shows, several of us also reproduced the exact same "user not found" / no-IdP-redirect behavior on Login V1, across multiple releases (v4.5.0, v4.6.3, v4.7.0, v4.11.0). Could you confirm:

- Is the Login V1 domain discovery regression in scope for any of #12021 / #12023 / #12024 / #12025, or does it need its own ticket?
- Since we're still on Login V1 (V2 has other blocking issues for us), can you confirm the V4 fixes will explicitly cover V1 as well, not just V2?

Also still pending from earlier: can you confirm the multi-domain-same-org routing scenario jackson@verified-domain.com → external IdP, alice@gmail.com → local password, same org) is expected to work on Login V1 once these fixes land?

Thank you for your help

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing older `area/console` issues.

We're building a replacement for the Console with significantly better usability, and that's where our focus is right now. As a result, the current Console is planned for deprecation over the next 12 months, and we're not prioritizing fixes or improvements to it in the meantime.

If this is still an active problem for you, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.

**Comment by elinashoko** [comment]
Ping, we will keep this open
