### ISSUE TITLE
[Bug]: Username Password not allowed! when Identity Providers configured with Login v2

### ISSUE THREAD

**Issue by micael-pn** [zitadel/zitadel#10671]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

4.1.0

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

Using login V2, when I enable an external Identity Provider (SAML or OIDC) for an organization and try to log in with a user from that organization after having disabled the password connection beforehand, I receive the error "Username Password not allowed! Contact your administrator for more information." whereas I expect to be redirected to the IdP's page. This is, by the way, the behavior on login v1.

### To reproduce

1. Enable Login V2 UI
2. Add an organization
3. Configure an external IdP for the organization with the following settings (we tested with Mock SAML and Google)
<img width="1321" height="1805" alt="Image" src="https://github.com/user-attachments/assets/b03102d2-c598-4c2a-8a6a-9e65e9a23955" />

4. Configure the organization with the following Login Behavior and Security settings

<img width="528" height="740" alt="Image" src="https://github.com/user-attachments/assets/575f2d3e-b5ca-46d3-9c5b-cedb06d6954a" />

5. Add a verified domain for that organization and set it as default
6. Add a user using the same domain
7. Try to login entering the user email
8. You should get the error "Username Password not allowed!"

<img width="527" height="676" alt="Image" src="https://github.com/user-attachments/assets/28ab7239-3ed7-4892-8704-c6d9c5a6f49a" />

### Expected behavior

I expect the same behavior as Login V1 : when a user exists in an organization where an External IdP is configured and the user's domain matches one of the verified domains configured for that organization, the user should be redirected to the external IdP in order to complete the login process

### Operating System

Device : Macbook Air M4
Browser : Chrome 139.0.7258.139

**Comment by micael-pn** [comment]
Hello,
Do you have any update to share regarding this issue ? It seems related to this one : https://github.com/zitadel/zitadel/issues/10662

If domain discovery doesn't work anymore since V4 release, this looks quite important to me since it is an important feature of the product. If not, do you have any workaround or advice ?

Thank you !

**Comment by micael-pn** [comment]
Hello @elinashoko @peintnermax ,
Has this issue been confirmed as a bug ? Do you have any update to share or any workaround to suggest ?
Thank you !

**Comment by elinashoko** [comment]
Hey @micael-pn apologies for the delay. @peintnermax can you please have a look at this?

**Comment by micael-pn** [comment]
Hi @elinashoko @peintnermax ,
This seems quite an important bug since Domain Discovery, one of the most important feature for multi-tenancy use cases, is not working with the new Login V2. At the moment, it blocks the release of Zitadel for our solution since it is a requirement. Do you have any update or workaround to share ?
Thank you very much for your help !

**Comment by peintnermax** [comment]
> Hi [@elinashoko](https://github.com/elinashoko) [@peintnermax](https://github.com/peintnermax) , This seems quite an important bug since Domain Discovery, one of the most important feature for multi-tenancy use cases, is not working with the new Login V2. At the moment, it blocks the release of Zitadel for our solution since it is a requirement. Do you have any update or workaround to share ? Thank you very much for your help !

Hi @micael-pn ,

We've been working on a fix for this issue and will provide a new version including the fix soon.
Domain discovery was fixed with https://github.com/zitadel/zitadel/pull/10729 and will be part of the same version.

**Comment by micael-pn** [comment]
Thank you very much. We are looking forward to use Zitadel in our product, thanks to this fix !

**Comment by micael-pn** [comment]
Hello @elinashoko @peintnermax ,
Unfortunately, the issue still happens with v4.3.1

Domain discovery is enabled for both Default settings and the Organization Test SAML

<img width="1920" height="3016" alt="Image" src="https://github.com/user-attachments/assets/b8bb1362-2f69-4095-ae16-c2dd6d533eea" />
<img width="1920" height="2901" alt="Image" src="https://github.com/user-attachments/assets/4c24cec6-4500-452b-b37d-5c5ddf6a3bed" />

Domain example.com is set as Verified Domain for the Organization Test SAML

<img width="1920" height="963" alt="Image" src="https://github.com/user-attachments/assets/9c5c2093-2aaa-414e-ae82-bbc60df897ab" />

With Login V1, I am correctly redirected to Mock SAML external Idp

https://github.com/user-attachments/assets/55315b74-e996-4fd4-9887-b5908514352f

With Login V2, the issue Username Password not allowed! still appears 

https://github.com/user-attachments/assets/45dee135-67de-4ce0-a585-a189208354e6

Am I missing something ?

Thank you

**Comment by elinashoko** [comment]
Heya @micael-pn, we'll have a look and get back to you, thanks for your patience. I've reopened the issue.

**Comment by micael-pn** [comment]
Hi @elinashoko ,
I see that the issue has been closed 3 days ago but there is still no build available. Do you have any ETA for that new build to be released ?
THanks !

**Comment by micael-pn** [comment]
Hello @elinashoko @peintnermax ,
We are still experiencing the same issue described [in this comment](https://github.com/zitadel/zitadel/issues/10671#issuecomment-3380915357) with the last release v4.5.0.
Am I missing something ?
