### ISSUE TITLE
Passkey/WebAuthn login ends in **endless loop**

### ISSUE THREAD

**Issue by JSchmie** [zitadel/zitadel#10818]
## Environment
- **Zitadel (server):** `ghcr.io/zitadel/zitadel:latest` (also tested with `4.2.2`)
- **Login UI:** `ghcr.io/zitadel/zitadel-login:latest` (also tested with `4.2.2`)
- **DB:** Postgres 17-alpine
- **Reverse proxy:** Traefik v3.5 (TLS at proxy; upstream to Zitadel via h2c)
- **Hosting:** self-hosted via Docker Compose (Linux)
- **Primary domain:** `<YOUR_DOMAIN>` (single domain used for login; passkeys registered on this domain)
- **Clients tried:** Windows Hello, Android/iOS Google passkey, Bitwarden passkeys; Firefox, Chrome, Edge (private sessions, extensions off)
- **What works:** Console loads, API endpoints respond, non-passkey login flows work; **only passkey login loops**

## Summary
Signing in with **Passwordless / Passkey** consistently results in an **endless loop**: the browser prompts for the passkey, I approve it, the page reloads **without any error**, and I’m asked for a passkey again.  
Everything else in the deployment appears healthy; this issue is *only* with passkey sign-in.

## Steps to reproduce
1. Go to `https://<YOUR_DOMAIN>/ui/console` (Hosted Login V2 enabled).
2. Click **Passwordless / Passkey**.
3. Approve the passkey prompt (reproduces across multiple devices and browsers).
4. Observe: the page reloads and returns to the passkey prompt (no error shown).

## Expected
After a successful passkey assertion, the session should finalize and redirect to Console (or the OIDC callback).

## Actual
- The passkey prompt appears and I approve it.
- The follow-up page load **does not** complete the session; the UI reloads and asks for a passkey again.
- **No error** is displayed in the UI.

---

## Observations (sanitized)

<details>
<summary>Traefik access logs (sanitized)</summary>

```
<CLIENT_IP> - - [<TS>] "POST /ui/v2/login/passkey?loginName=<LOGIN_NAME>&altPassword=true&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID> HTTP/2.0" 200 7244 "https://<YOUR_DOMAIN>/ui/v2/login/passkey?loginName=<LOGIN_NAME>&altPassword=true&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID>" "<UA>" <REQ_ID> "zitadel-login@docker" "http://<LOGIN_CONTAINER_IP>:3000" 280ms

<CLIENT_IP> - - [<TS>] "GET /ui/v2/login/login?sessionId=<SESSION_ID>&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID>&_rsc=<RSC_TOKEN> HTTP/2.0" 500 29 "https://<YOUR_DOMAIN>/ui/v2/login/passkey?loginName=<LOGIN_NAME>&altPassword=true&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID>" "<UA>" <REQ_ID> "zitadel-login@docker" "http://<LOGIN_CONTAINER_IP>:3000" 14ms

# Immediately after, similar GET (without _rsc) returns 307 and flow jumps back to /passkey:
<CLIENT_IP> - - [<TS>] "GET /ui/v2/login/login?sessionId=<SESSION_ID>&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID> HTTP/2.0" 307 0 "https://<YOUR_DOMAIN>/ui/v2/login/passkey?loginName=<LOGIN_NAME>&altPassword=true&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID>" "<UA>" <REQ_ID> "zitadel-login@docker" "http://<LOGIN_CONTAINER_IP>:3000" 250ms

<CLIENT_IP> - - [<TS>] "GET /ui/v2/login/passkey?loginName=<LOGIN_NAME>&altPassword=true&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID> HTTP/2.0" 200 11782 "https://<YOUR_DOMAIN>/ui/v2/login/passkey?loginName=<LOGIN_NAME>&altPassword=true&requestId=oidc_V2_<REQUEST_ID>&organization=<ORG_ID>" "<UA>" <REQ_ID> "zitadel-login@docker" "http://<LOGIN_CONTAINER_IP>:3000" 174ms
```
(Loop repeats with new session IDs)
</details>

<details>
<summary>Login UI container logs (sanitized)</summary>

```
Login with session: <SESSION_ID> and authRequest: V2_<REQUEST_ID>
Found session <SESSION_ID>
Session has no valid totpEmail factor undefined
Session is valid: false
No session lifetime provided, using default of 24 hours.
⨯ [Error: Couldn't find all resumable slots by key/index during replaying. The tree doesn't match so React will fallback to client rendering.] {
  digest: '3186981323'
}
No lifetime provided for session, defaulting to 24 hours
```
</details>

<details>
<summary>Zitadel API container logs (sanitized excerpt)</summary>

```
time="<TS>" level=info ... domain="https://<YOUR_DOMAIN>" grpcStatus=0 httpStatus=200 ... method=/zitadel.settings.v2.SettingsService/GetHostedLoginTranslation ...
time="<TS>" level=info ... method=/zitadel.settings.v2.SettingsService/GetBrandingSettings ...
time="<TS>" level=info ... method=/zitadel.user.v2.UserService/ListAuthenticationMethodTypes ...
time="<TS>" level=info ... method=/zitadel.settings.v2.SettingsService/GetLoginSettings ...
time="<TS>" level=info ... method=/zitadel.session.v2.SessionService/CreateSession ...
time="<TS>" level=info ... method=/zitadel.session.v2.SessionService/SetSession ...
```
Settings + Session APIs return 200; API path appears healthy.)
</details>

---

## Configuration (current)

<details>
<summary>docker-compose.yaml</summary>

```yaml
services:
  zitadel:
    restart: unless-stopped
    image: ghcr.io/zitadel/zitadel:latest
    command: start-from-init --masterkey "${ZITADEL_MASTERKEY}" --tlsMode external
    environment:
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_DOMAIN}           # <YOUR_DOMAIN>
      ZITADEL_EXTERNALPORT: "443"
      ZITADEL_EXTERNALSECURE: "true"
      ZITADEL_TLS_ENABLED: "false"

      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${ZITADEL_DATABASE_POSTGRES_USER_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable

      ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: /current-dir/login-client.pat
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: login-client
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: Automatically Initialized IAM_LOGIN_CLIENT
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: '2029-01-01T00:00:00Z'

      # Hosted Login V2 feature flags
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: true
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: https://${ZITADEL_DOMAIN}/ui/v2/login

      # Left enabled during testing (can remove if recommended)
      ZITADEL_OIDC_DEFAULTLOGINURLV2: https://${ZITADEL_DOMAIN}/ui/v2/login/login?authRequest=
      ZITADEL_OIDC_DEFAULTLOGOUTURLV2: https://${ZITADEL_DOMAIN}/ui/v2/login/logout?post_logout_redirect=
      ZITADEL_SAML_DEFAULTLOGINURLV2: https://${ZITADEL_DOMAIN}/ui/v2/login/login?samlRequest=

      ZITADEL_FIRSTINSTANCE_PATPATH: /current-dir/admin.pat
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME: admin
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME: Automatically Initialized IAM_OWNER
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE: 1

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # API/console → 8080 (h2c)
      - "traefik.http.routers.zitadel-api.rule=Host(`${ZITADEL_DOMAIN}`) && !PathPrefix(`/ui/v2/login`)"
      - "traefik.http.routers.zitadel-api.entrypoints=websecure"
      - "traefik.http.routers.zitadel-api.tls=true"
      - "traefik.http.routers.zitadel-api.service=zitadel-api"
      - "traefik.http.services.zitadel-api.loadbalancer.server.port=8080"
      - "traefik.http.services.zitadel-api.loadbalancer.server.scheme=h2c"

      # Login v2 → 3000
      - "traefik.http.routers.zitadel-login.rule=Host(`${ZITADEL_DOMAIN}`) && PathPrefix(`/ui/v2/login`)"
      - "traefik.http.routers.zitadel-login.entrypoints=websecure"
      - "traefik.http.routers.zitadel-login.tls=true"
      - "traefik.http.routers.zitadel-login.service=zitadel-login"
      - "traefik.http.services.zitadel-login.loadbalancer.server.port=3000"
      - "traefik.http.routers.zitadel-login.tls.certresolver=lets-encrypt-resolver"

    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

    volumes:
      - .:/current-dir:delegated

    networks:
      - zitadel
      - traefik

    depends_on:
      db:
        condition: service_healthy

  login:
    restart: unless-stopped
    image: ghcr.io/zitadel/zitadel-login:latest
    environment:
      - ZITADEL_API_URL=http://zitadel:8080
      - NEXT_PUBLIC_BASE_PATH=/ui/v2/login
      - ZITADEL_SERVICE_USER_TOKEN_FILE=/current-dir/login-client.pat
      - CUSTOM_REQUEST_HEADERS=Host:${ZITADEL_DOMAIN}
    network_mode: service:zitadel
    volumes:
      - .:/current-dir:ro
    depends_on:
      zitadel:
        condition: service_healthy
        restart: false

  db:
    restart: unless-stopped
    image: postgres:17-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    networks:
      - zitadel

networks:
  zitadel:
  traefik:
    external: true
```
</details>

What I already tried

Ensured one serving host only and re-registered passkeys on that same host.

Tested across browsers/devices (Windows Hello, Google passkey on phone, Bitwarden), private sessions, extensions disabled.

Tried leaving the Login V2 Base URI blank vs explicitly set — no change.

Temporarily relaxed MFA enforcement to rule out second-factor invalidation.

All non-passkey flows work; only passkey login loops.

### Related issues (similar symptoms)

Login V2: unexpected RSC/_rsc requests to /login causing reloads — #10629

WebAuthn begin/login failures in Session API — #8282

Login V2 loop when session/user state invalid — #10307

Passkey/WebAuthn UX & flows (Autofill / Conditional UI) — #8899

Passwordless-only pitfalls / lockout risk — #8995

**Comment by JustWilder** [comment]
I have this exact same issue. Pretty much been thru the same process as OP and have the same logs output. Only difference is that my instance is running on Kubernetes. 
Its installed using the official helm chart and recently upgraded from 8.13.4 to 9.5.3. Created a machine user and setup the login-client secret. 
The rest is mentioned by OP.

**Comment by peintnermax** [comment]
Hey @JSchmie and @JustWilder can you reproduce this with the newest version v4.4.0 or verify this issue has been fixed? We've implemented several improvements for ensuring the sessions are validated correctly which should prevent this loop from happening. Thank you!

**Comment by JSchmie** [comment]
Hi @peintnermax, I tested v4.4.0 as requested and the login issue persists. After the upgrade I created a new passkey to avoid legacy errors, but none of my devices presented a passkey prompt (neither Bitwarden on my laptop nor the Android fingerprint/passkey). At the same time, the password login option didn’t appear, so I couldn’t sign in at all. After I deleted the passkey as an admin, the password login reappeared and worked.

**Comment by JustWilder** [comment]
I jumped straight to 4.5.0 which is available at this time and im just confirming what @JSchmie has already informed. No passkey prompt at all now.

**Comment by peintnermax** [comment]
> I jumped straight to 4.5.0 which is available at this time and im just confirming what [@JSchmie](https://github.com/JSchmie) has already informed. No passkey prompt at all now.

We've identified this issue and have already provided the fix for it which will come soon. https://github.com/zitadel/zitadel/pull/10991
If the issue persists with 4.5.1 we'd appreciate to have a HAR file that demonstrates the infinite loop to get a better understanding of your setup. Please send it to support@zitadel and reference this issue. Thank you!

**Comment by JSchmie** [comment]
@peintnermax for me, the latest version fixed the bug. Thanks a lot.

**Comment by JustWilder** [comment]
@peintnermax same here. All is working. Thank you for a fairly quick fix!

**Comment by peintnermax** [comment]
That's great news. We're very glad to hear that it's working for you now. Closing this issue. 😎
