### ISSUE TITLE
OAuthErrorEvent: unable to retrieve client by id since version 2.5.0

### ISSUE THREAD

**Issue by lapin-b** [zitadel/zitadel#4604]
**Describe the bug**

The server reports an error that the web browser shows in its console, when accessing the web UI at `/ui/console` whenever the user is logged in or not. The errors are reported from version 2.5.0 and onwards (to anybody reading this from the future, the current version is 2.10.0).

In the not logged in state, the following OAuth message is reported by the server:

(The JSON payload has been formatted for readability)
```
Uncaught (in promise): OAuthErrorEvent: 
{
    "type": "code_error",
    "reason": {},
    "params": {
        "error": "server_error",
        "error_description": "unable+to+retrieve+client+by+id",
        "state": "<redacted>"
    }
}
```

In the logged in state, seemingly related errors are returned by the server in the GRPC calls. A message in the browser console is:

> could not read projectid by clientid (AUTH-GHpw2)

The payloads sent by the server don't have more information that I can copy-paste here for examination.

**To Reproduce**
The same client application behavior can be observed when logged in and not logged in, except for the messages reported in the browser console.

1. Visit `/ui/console`
2. The page visible to the user has no content (see screenshot).
3. Open the browser dev tools console
4. Notice the error(s)

**Expected behavior**
I expect to be redirected to the login page or have the console with the required data, whichever is relevant according to the login state of the user.

**Screenshots**

![A "blank" page with no error presented to the user](https://user-images.githubusercontent.com/3647174/197487825-5d32a3ae-32ec-4afd-827f-89374ffb0657.png)

**Desktop:**
Server side error, not applicable.

**Smartphone:**
Server side error, not applicable.

**Server:**
OS: Debian 11.5
Database: PostgreSQL 14

**Comment by eliobischof** [comment]
@adlerhurst can you please describe a planned solution and a workaround?

**Comment by livio-a** [comment]
Hey @lapin-b 

There was an issue with indexes on postgres, because in contrast to cockroach where indexes must be unique on a table, postgres requires uniqueness in the schema. We resolved it with https://github.com/zitadel/zitadel/pull/4439, release with version 2.6.0.

Is it possible for you to upgrade to 2.6.0?
As a workaround you could rename the indexes on table projections.apps2 and projections.keys2.

**Comment by lapin-b** [comment]
Hello @livio-a

Thanks for the answer. I have upgraded to version 2.6.0 ─ it's a matter of running an Ansible playbook ─ and I have renamed the indexes on the tables `projections.apps2` and `projections.keys2` according to the following SQL statements and your suggestions:

```sql
-- Table projections.apps2
ALTER INDEX projections.app_id_unique RENAME TO app2_id_unique;
ALTER INDEX projections.app_project_id_idx RENAME TO app2_project_id_idx;
ALTER INDEX projections.apps2_pkey RENAME TO apps2_2_pkey;

-- Table projections.keys2
ALTER INDEX projections.key_id_unique RENAME TO key2_id_unique;
ALTER INDEX projections.keys2_pkey RENAME TO keys2_2_pkey;
```

I've restarted the service; the same errors are still present.

**Comment by eliobischof** [comment]
@lapin-b sorry for the delay. I guess you still have the issue above?

**Comment by lapin-b** [comment]
@eliobischof Yes, the issue is still a thing. As a reminder, I've switched to version 2.6.0 and edited a few indexes on the database according to the SQL queries I have written.

**Comment by CMiksche** [comment]
I have the same Issue. Tried out different versions from 2.12 to 2.6 (not 2.13 because of #4739) but the Issue is still there.

I also checked the indexes and they seem to be correctly updated:

```
Indexe:
    "apps3_pkey" PRIMARY KEY, btree (instance_id, id)
    "app3_id_unique" UNIQUE CONSTRAINT, btree (id)
    "app3_project_id_idx" btree (project_id)
Fremdschlüsselverweise von:
    TABLE "projections.apps3_api_configs" CONSTRAINT "fk_api_ref_apps3" FOREIGN KEY (instance_id, app_id) REFERENCES projections.apps3(instance_id, id) ON DELETE CASCADE
    TABLE "projections.apps3_oidc_configs" CONSTRAINT "fk_oidc_ref_apps3" FOREIGN KEY (instance_id, app_id) REFERENCES projections.apps3(instance_id, id) ON DELETE CASCADE
    TABLE "projections.apps3_saml_configs" CONSTRAINT "fk_saml_ref_apps3" FOREIGN KEY (instance_id, app_id) REFERENCES projections.apps3(instance_id, id) ON DELETE CASCADE
```

**Comment by adlerhurst** [comment]
@lapin-b from which version did you want to update? I started with zitadel v2.5.0 and updated to v2.6.0 without any issues. We will deploy 2.13.1 also as stable. We fixed a lot of bugs for version updates and postgres. It might be a good soloution to update to this version later this week?

**Comment by lapin-b** [comment]
I have tried upgrading from 2.4.0 to 2.5.0 when the latter has been released. I imagine that the current issue has been fixed somehow ? I'll check when 2.13.1 is released.

I've upgraded to 2.13.0, some errors regarding the database migration appeared. Those have been reported with #4739 and fixed with #4740.

**Comment by CMiksche** [comment]
I upgraded to the new 2.13.1 version from today, restarted the service and still get the same Issue:

```
ERROR Error: Uncaught (in promise): OAuthErrorEvent: {"type":"code_error","reason":{},"params":{"error":"server_error","error_description":"unable+to+retrieve+client+by+id","state":"<...>"}}
```

I also get lots of the following messages:

```
level=warning msg="unable to update failure count" caller="/home/runner/work/zitadel/zitadel/internal/eventstore
level=error msg="trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler
```

**Comment by adlerhurst** [comment]
okay thanks. I think we have a timing issue here. Sometimes it works sometimes not. We are working on a much simpler solution but this takes some time.

You should be able to see failed events here: {your-url}/ui/console/failed-events

The easiest solution for the moment is to reset the projection by following these steps, they will trigger zitadel to recompute the projections:

if you use zitadel version < v2.5.0 replace 'apps3' with 'apps2'

```
1. shutdown zitadel
2. connect to the zitadel database
3. set the schema:
  1. postgres: `SET search_path TO projections;`
  2. crdb: `USE projections;`
4.  `TRUNCATE apps3 CASCADE;`
5. `DELETE FROM current_sequences WHERE projection_name = 'projections.apps3'`
6. restart ZITADEL
```

ZITADEL now starts to recompute the projection, this can take some minutes, depending on the amount of events.

I hope this helps.

**Comment by CMiksche** [comment]
I followed the steps (did it for `apps2` and `apps3`), but still have the same Issue.

> If this does not help please send me the result of the following sql stmt: `select projection_name, failure_count from failed_events;`

Here is my result:

```
zitadel=# select projection_name, failure_count from failed_events;

 projections.apps3           |             5
 projections.login_policies3 |             5
 projections.keys3           |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.login_policies3 |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.login_policies3 |             5
 projections.login_policies3 |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.login_policies3 |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.login_policies3 |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.apps3           |             2
 projections.apps3           |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.apps3           |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.users5          |             5
 projections.users5          |             4
```

**Comment by adlerhurst** [comment]
hm this looks strange. If you reset the projection the failure count should be 6 if zitadel was failed to reduce an event. Do you get any result if you execute `SELECT name FROM apps3`?

If not please try this one:

1. shutdown zitadel
2. connect to the zitadel database
3. set the schema:
   1. postgres: `SET search_path TO projections;`
   2. crdb: `USE projections;`
4. `TRUNCATE apps3 CASCADE; TRUNCATE users5 CASCADE; TRUNCATE login_policies3 CASCADE; TRUNCATE keys3 CASCADE;`
5. `DELETE FROM current_sequences WHERE projection_name IN ('projections.apps3', 'projections.users5', 'projections.login_policies3', 'projections.keys3');`
6. `DELETE FROM failed_events WHERE projection_name IN ('projections.apps3', 'projections.users5', 'projections.login_policies3', 'projections.keys3');`
7. `DELETE FROM locks WHERE projection_name IN ('projections.apps3', 'projections.users5', 'projections.login_policies3', 'projections.keys3');`
8. restart ZITADEL v2.13.1

**Comment by adlerhurst** [comment]
okay wait a moment I have to check something, which would explain the different behaviour between my installation and yours

**Comment by adlerhurst** [comment]
I found a workaround which is not recommend for production use. I'm working on a fix but this might take a bit.

The workaround:

1. shutdown zitadel
2. connect to the zitadel database
3. set the schema:
   1. postgres: `SET search_path TO projections;`
   2. crdb: `USE projections;`
4. the following statements reset all projections you had failed events
```sql
-- ensure no locks are set from stopped zitadel
DELETE FROM locks WHERE projection_name IN ('projections.apps3', 'projections.users5', 'projections.login_policies3', 'projections.keys3');

-- truncate
TRUNCATE apps3 CASCADE; 
TRUNCATE users5 CASCADE; 
TRUNCATE login_policies3 CASCADE; 
TRUNCATE keys3 CASCADE;

-- reset current sequences
DELETE FROM current_sequences WHERE projection_name IN ('projections.apps3', 'projections.users5', 'projections.login_policies3', 'projections.keys3');

-- reset failed events
DELETE FROM failed_events WHERE projection_name IN ('projections.apps3', 'projections.users5', 'projections.login_policies3', 'projections.keys3');

-- now the ugly part where we change the past, this is NOT recommended for production
 UPDATE eventstore.events 
    SET event_data = NULL 
  WHERE aggregate_type = 'system' 
    AND aggregate_id = 'SYSTEM' 
    AND event_type = 'system.projections.scheduler.succeeded' 
    AND (
        event_data @> '{"name":"projections.apps3"}'
     OR event_data @> '{"name":"projections.users5"}'
     OR event_data @> '{"name":"projections.login_policies3"}'
     OR event_data @> '{"name":"projections.keys3"}'
    );
```
5. restart ZITADEL v2.13.1

**Comment by lapin-b** [comment]
The workaround seems to work properly on my installation, though time travelling might not be a good idea, as you've said in the comments of the SQL snippet. :grin: 

Nonetheless, accessing `/` redirects to `/ui/console` and finally to `/ui/login/login?...` without any errors. I can complete the login flow to the console, and an external application using Oauth2 with OIDC.

**Comment by adlerhurst** [comment]
Happy to hear that 😁 yes it's a huge anti pattern 😅 i will link the branch for this fix as soon as possible

**Comment by CMiksche** [comment]
@adlerhurst After applying the workaround I get a different error: "Es ist ein interner Fehler aufgetreten (Internal)".

`SELECT name FROM apps3;` returns " Management-API, Admin-API, Auth-API, Console" and my own Apps.

`TRUNCATE users5 CASCADE;` and `TRUNCATE login_policies3 CASCADE;` doesn't work on my system because it doesn't exist. Maybe that's the problem with my system?

I also still get the following errors:

```
zitadel[29549]: time="2022-11-29T12:24:14+01:00" level=warning msg="unable to update failure count" caller="/home/runner/work/zitadel/zitadel/internal/eventstore>
zitadel[29549]: time="2022-11-29T12:24:14+01:00" level=error msg="trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_p>
zitadel[29549]: time="2022-11-29T12:24:14+01:00" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go>
zitadel[29549]: time="2022-11-29T12:31:58+01:00" level=error msg="error loading login policy" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/log>
```

`failed_events` is now empty:

```
select projection_name, failure_count from failed_events;
 projection_name | failure_count 
-----------------+---------------
(0 Zeilen)
```

**Comment by adlerhurst** [comment]
Which version of zitadel do you use? It looks like you are using an older version than v2.13.1

**Comment by CMiksche** [comment]
> Which version of zitadel do you use? It looks like you are using an older version than v2.13.1

No, the current version:

```
zitadel -v
zitadel version 2.13.1
```

But maybe the migrations failed?

**Comment by adlerhurst** [comment]
oh sorry my mistake, if you switched to v2.13.1 after you did the database operations it's possible that the tables did not exist before.

Do you get the error on the login screen? Do you get an error id if you hover over the error?

**Comment by CMiksche** [comment]
> Do you get the error on the login screen? Do you get an error id if you hover over the error?

I get the error on the login screen directly after visiting the URL - I can't even login.

I only get "An internal error occurred (Internal)", in the URL is the `authRequestID` but no other information is shown - neither in the console nor when I hover or look in the source code of the page.

Systemd also only outputs the messages which I already posted in https://github.com/zitadel/zitadel/issues/4604#issuecomment-1330489060

Luckily I currently use Zitadel just on a dev instance without any production use - so I could also completly setup everything new from the beginning... But would there be a way to import the Apps and Instance settings? (Like my custom logo, colors, texts...)

**Comment by adlerhurst** [comment]
I think the existing events are not the problem, thats why I think we should try the following:

1. shutdown zitadel
2. delete the schemas for the projections:  
```sql
DROP SCHEMA projections CASCADE;
DROP SCHEMA auth CASCADE;
DROP SCHEMA adminapi CASCADE;

CREATE SCHEMA projections;
```
3. create the schemas and required tables by executing these statements:
   -  https://github.com/zitadel/zitadel/blob/v2.13.1/cmd/setup/01_sql/adminapi.sql
   -  https://github.com/zitadel/zitadel/blob/v2.13.1/cmd/setup/01_sql/auth.sql
   -  https://github.com/zitadel/zitadel/blob/v2.13.1/cmd/setup/01_sql/projections.sql
   -  https://github.com/zitadel/zitadel/blob/v2.13.1/cmd/setup/05.sql
4. execute the following statement to tell zitadel to recompute the projections (not recommended for production systems):  
```sql
UPDATE eventstore.events
    SET event_data = NULL
  WHERE aggregate_type = 'system'
    AND aggregate_id = 'SYSTEM'
    AND event_type = 'system.projections.scheduler.succeeded';
```
5. `zitadel start-from-init`
6. give zitadel some time to start

**Comment by CMiksche** [comment]
Now I had to set the rights again:

`GRANT USAGE ON SCHEMA projections,auth,adminapi TO <myuser>;`

And also the ownership of all new tables:

`ALTER TABLE auth.locks OWNER TO <myuser>;`

I started it afterwards and `start-from-init` failed because 

```
caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:51" error="FEHLER: Relation »current_sequences_instance_id_idx« existiert bereits (SQLSTATE 42P07)"
caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:112" error="FEHLER: Relation »current_sequences_instance_id_idx« existiert bereits (SQLSTATE 42P07)"
```

While `start` failed because:

`FEHLER: Relation »projections.instances« existiert nicht (SQLSTATE 42P01)`

But when I try to delete `current_sequences_instance_id_idx`, it shows me the following error:

```
DROP INDEX current_sequences_instance_id_idx;
FEHLER:  Index »current_sequences_instance_id_idx« existiert nicht
```

So I created a PR for that: https://github.com/zitadel/zitadel/pull/4798

**Comment by adlerhurst** [comment]
hi @CMiksche the new release v2.14.0 will rise another error. Please wait for v2.14.1 before you upgrade

**Comment by adlerhurst** [comment]
Hi @CMiksche I think v2.14.1 is worth a try. It will create a lot of new projection tables because we had to add a new field to them.

**Comment by CMiksche** [comment]
Tried it out with 2.14.1, had to change the permissions first:

```
ALTER SCHEMA auth OWNER TO <myuser>;
ALTER SCHEMA projections OWNER TO <myuser>;
```

Then I got the following errors while starting with `start-from-init`:

```
ERRO[0000] migration failed caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:51" error="FEHLER: Spalte »last_failed« von Relation »failed_events« existiert bereits (SQLSTATE 42701)"
FATA[0000] unable to migrate step 5 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:113" error="FEHLER: Spalte »last_failed« von Relation »failed_events« existiert bereits (SQLSTATE 42701)"
```

@adlerhurst I created a PR again for this: https://github.com/zitadel/zitadel/pull/4812

When starting with `start` I get errors, that many relations like the following don't exists:

```
(/home/runner/work/zitadel/zitadel/internal/view/repository/requests.go:42) 
[2022-12-02 11:15:34]  FEHLER: Relation »adminapi.styling2« existiert nicht (SQLSTATE 42P01) 

(/home/runner/work/zitadel/zitadel/internal/view/repository/requests.go:140) 
[2022-12-02 11:15:34]  FEHLER: Relation »auth.user_external_idps2« existiert nicht (SQLSTATE 42P01) 

FEHLER: Relation »projections.instances« existiert nicht (SQLSTATE 42P01)
```

**Comment by CMiksche** [comment]
Same Issue like `start-from-init`:

```
ERRO[0000] migration failed caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:51" error="FEHLER: Spalte »last_failed« von Relation »failed_events« existiert bereits (SQLSTATE 42701)"
FATA[0000] unable to migrate step 5 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:113" error="FEHLER: Spalte »last_failed« von Relation »failed_events« existiert bereits (SQLSTATE 42701)"
```

Unfortunately, the script stops at that Issue and doesn't continue...

Is there a good documentation how to build Zitadel from Source? Then I could try debugging it...

**Comment by mzch** [comment]
Well, isn't this issue fixed?. no error in log, but login page never shows.
<img width="1476" alt="スクリーンショット 2022-12-03 4 22 25" src="https://user-images.githubusercontent.com/621178/205369990-f63c354f-ba3d-4a87-ac0f-07ed565cede9.png">

- log
```
Dec  3 04:21:48 ls systemd[1]: Started Zitadel - Identity Provider.
Dec  3 04:21:48 ls zitadel[1615338]: time="2022-12-03T04:21:48+09:00" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:61"
Dec  3 04:21:48 ls zitadel[1615338]: time="2022-12-03T04:21:48+09:00" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=190443059274631625 workers=1
Dec  3 04:21:48 ls zitadel[1615338]: time="2022-12-03T04:21:48+09:00" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=190443059274697161 workers=1
Dec  3 04:21:49 ls zitadel[1615338]: time="2022-12-03T04:21:49+09:00" level=info msg="server is listening on [::]:8001" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:255"
```

**Comment by adlerhurst** [comment]
> Same Issue like `start-from-init`:
> 
> ```
> ERRO[0000] migration failed caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:51" error="FEHLER: Spalte »last_failed« von Relation »failed_events« existiert bereits (SQLSTATE 42701)"
> FATA[0000] unable to migrate step 5 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:113" error="FEHLER: Spalte »last_failed« von Relation »failed_events« existiert bereits (SQLSTATE 42701)"
> ```
> 
> Unfortunately, the script stops at that Issue and doesn't continue...

in v2.14.2 your pr was merged

> 
> Is there a good documentation how to build Zitadel from Source? Then I could try debugging it...

Please have a look at [our contribution guide](https://github.com/zitadel/zitadel/blob/main/CONTRIBUTING.md#backend--login).

**Comment by adlerhurst** [comment]
> Well, isn't this issue fixed in `v2.14.2`?. no error in log, but login page never shows. <img alt="スクリーンショット 2022-12-03 4 22 25" width="1476" src="https://user-images.githubusercontent.com/621178/205369990-f63c354f-ba3d-4a87-ac0f-07ed565cede9.png">
> 
> * log
> 
> ```
> Dec  3 04:21:48 ls systemd[1]: Started Zitadel - Identity Provider.
> Dec  3 04:21:48 ls zitadel[1615338]: time="2022-12-03T04:21:48+09:00" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:61"
> Dec  3 04:21:48 ls zitadel[1615338]: time="2022-12-03T04:21:48+09:00" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=190443059274631625 workers=1
> Dec  3 04:21:48 ls zitadel[1615338]: time="2022-12-03T04:21:48+09:00" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=190443059274697161 workers=1
> Dec  3 04:21:49 ls zitadel[1615338]: time="2022-12-03T04:21:49+09:00" level=info msg="server is listening on [::]:8001" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:255"
> ```

Did you open the console instantly after the last log entry showed up? please try {host}/ui/login. If this does not work please let me know

**Comment by CMiksche** [comment]
> in v2.14.2 your pr was merged

Now I only get the Issue `ID=QUERY-n0wng Message=Instanz nicht gefunden` on the web UI when I execute `start-from-setup`... (Same message when I execute `start`)

When I do `select * from projections.instances;`, no result appears - so looks like I have to setup everything new again to fill the tables.

I tried executing the `start-from-setup` together with `DefaultInstance` in the config file but still the same Error was shown.

Previously (before upgrading), my instance config was existing and all the customised colours and links showed correctly on the Frontend.

**Comment by adlerhurst** [comment]
hi @CMiksche 

sorry to hear that. Most projections were recreated with v2.14. but the instance table wasn't.

Just to be sure. Your ZITADEL database user is granted full access to the schemas and tables created manually? I used my zitadel user to test, thats why I forgot to mention these statements.

You can reset the instances projection as I've written below, but as I am not sure if all the projections are fixed after that you can also contact me via discord or email at support@zitadel.com where we can have a more detailed look at your data.

The workaround, as done before:

1. shutdown zitadel
2. connect to the zitadel database
3. set the schema:
   1. postgres: `SET search_path TO projections;`
   2. crdb: `USE projections;`
4. the following statements reset all projections you had failed events
```sql
-- ensure no locks are set from stopped zitadel
DELETE FROM projections.locks WHERE projection_name = 'projections.instances';

-- truncate
TRUNCATE projections.instances CASCADE;

-- reset current sequences
DELETE FROM projections.current_sequences WHERE projection_name = 'projections.instances';

-- reset failed events
DELETE FROM projections.failed_events WHERE projection_name = 'projections.instances';

-- now the ugly part where we change the past, this is NOT recommended for production
 UPDATE eventstore.events 
    SET event_data = NULL 
  WHERE aggregate_type = 'system' 
    AND aggregate_id = 'SYSTEM' 
    AND event_type = 'system.projections.scheduler.succeeded' 
    AND (
        event_data @> '{"name":"projections.instances"}'
    );
```
5. ZITADEL v2.14.2 `start-from-init`

**Comment by CMiksche** [comment]
I now simply created a new instance - as I already mentioned, in my case there was anyway just test and prototype data...

**Comment by hifabienne** [comment]
I will close this issue, since I think everyone got a running instance, we can reopen if we get some other problems
