### ISSUE TITLE
[Bug]: Custom scopes in access token break userinfo_endpoint

### ISSUE THREAD

**Issue by SchillingSebastian** [zitadel/zitadel#6292]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

**TLDR**: When adding custom scopes to the access token (I use a JWT) with an action, the token is no longer accepted/viable for the `userinfo` oidc endpoint.

Hey there 👋 
I have a custom action running which adds the users roles to the access token so that I can use them on my resource server to verify against. I now wanted to use this access token to get the userinfo from the oidc endpoint. This was not working. Fiddeling around I found out that if I remove the action extending the token, the access token works out as expected and returns my info. I do request the correct scopes ( `openid email profile urn:zitadel:iam:org:id:REDACTED offline_access`) which should allow me to request the userinfo.

Didn't find anything here on GH and just joined the DC (there doesn't seem to be anything on this as well)

### To reproduce

1. Configure Zitadel to add custom scopes to the access token
2. Log in user and obtain access token (with `oidc profile email` scopes), user must have a role assigned in the project
3. Use access token to request `userinfo_endpoint` data ([like described in the documentation](https://zitadel.com/docs/apis/openidoauth/endpoints#userinfo_endpoint))
4. Observe `access token invalid` answer for http request

### Expected behavior

Same behaviour as using an access token without custom added scopes. I would like to receive the users info according to the access tokens privileges.

### Relevant Configuration

Action -> FlowType Complement Token -> Pre access token creation: 
```JS
/**
 * Add each auhtorization role to the token scopes
 * as PROJECT_NAME:ROLE. Is required for the resource
 * server
 */
function addRolesToScope(ctx, api) {
    if (ctx.v1.user.grants == undefined || ctx.v1.user.grants.count == 0) {
        return;
    }
    let grants = [];
    ctx.v1.user.grants.grants.forEach(claim => {
        claim.roles.forEach(role => {
            grants.push(claim.projectName + ':' + role)
        })
    })
    api.v1.claims.setClaim('scope', grants)
}
```

Application token settings:
```Text
Auth Token Type: JWT
[x] Add user roles to the access token
[x] User roles inside ID Token
[x] User Info inside ID Token
```

### Additional Context

Feel free to tell me if you need more info. I can provide that asap :) 
Thanks!!

**Comment by SchillingSebastian** [comment]
The first thing I can imagine going wrong is me using a the `scope` claim to add my scopes. Maybe that messes with the server so that it won't assign actual scopes needed for the request? I thought I was on the safe side using these `scope` claim as you are not using it anywhere in the JWT

**Comment by SchillingSebastian** [comment]
Maybe this is realted to https://github.com/zitadel/zitadel/pull/6298?

**Comment by hifabienne** [comment]
> Maybe this is related to #6298?

Are you on self hosted? In that case it could relate.
But when you are on our cloud we deployed after you opened the issue.

**Comment by SchillingSebastian** [comment]
@hifabienne Yes i am self hosted. 
I pulled the newest docker release yesterday (v2.31.4), refreshed my access token, but i still receive `access token invalid`

**Comment by hifabienne** [comment]
@livio-a Can you help here?

**Comment by SchillingSebastian** [comment]
Maybe the token payload helps here as well
```Text
{
  "aud": [
    "REDACTED",
    "REDACTED",
    "REDACTED"
  ],
  "exp": 1691004857,
  "iat": 1690961657,
  "iss": "REDACTED",
  "jti": "225595938045952003",
  "nbf": 1690961657,
  "scope": [
    "REDACTED_PROJECT_NAME:USER"
  ],
  "sub": "REDACTED",
  "urn:zitadel:iam:org:id": "REDACTED",
  "urn:zitadel:iam:org:project:REDACTED:roles": {
    "USER": {
      "REDACTED": "REDACTED"
    }
  },
  "urn:zitadel:iam:org:project:roles": {
    "USER": {
      "REDACTED_ID": "REDACTED_DOMAIN"
    }
  },
  "urn:zitadel:iam:user:resourceowner:id": "REDACTED",
  "urn:zitadel:iam:user:resourceowner:name": "REDACTED",
  "urn:zitadel:iam:user:resourceowner:primary_domain": "REDACTED"
}

```

**Comment by livio-a** [comment]
I can reproduce the error, which really originates from using the `scope` claim. As initially defined by the Token Exchange (RFC8693: https://datatracker.ietf.org/doc/html/rfc8693#name-scope-scopes-claim):
> The value of the scope claim is a JSON string containing a space-separated list of scopes associated with the token, in the format described in [Section 3.3](https://www.rfc-editor.org/rfc/rfc6749#section-3.3) of [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)].

Therefore the verification of the access token will fail because of the format.

If possible I'd change the action to `api.v1.claims.setClaim('scope', grants.join(" "))` or use a different claim.

Is this an option for you @SchillingSebastian ?

**Comment by SchillingSebastian** [comment]
Yes this is works for me 👍 
Thanks!
