### ISSUE TITLE
[Bug]: 40_init_push_func_v2 migration hangs with PostgreSQL

### ISSUE THREAD

**Issue by CMiksche** [zitadel/zitadel#9180]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.67.2

### Database

PostgreSQL

### Database Version

17.2

### Describe the problem caused by this bug

When trying to upgrade from 2.67.1 to 2.67.2 the migration script hanged at the new 40_init_push_func_v2 migration. Afterwards a login or 2nd factor entering fails with an error stating that the SQL query doesn't match.

Error Message in UI:

```bash
ERROR: structure of query does not match function result type (SQLSTATE 42804) (Internal)
```

I rolled back to 2.67.1 and restored my database from a backup because of this - unfortunately, most error logs I entered in this issue reporting field here got deleted because my browser refreshed the field...

### To reproduce

1. Have an older version of Zitadel - e.g. 2.67.1 with PostgreSQL
2. Upgrade to 2.67.2 
3. Migration will hang
4. Login will not be possible because of the eventstore mismatch

**Comment by Avolicious** [comment]
Bug also exists if you jump from v2.67.1 to v.67.3.

**Comment by cr1cr1** [comment]
Confirm the above migrating from `v2.65.5` to `v2.66.1` or `v2.67.x`

**Comment by masewo** [comment]
Got this error when migrating from `v2.67.1` to `v2.67.2`. I went back manually to version `v2.67.1` as a temporary hot-fix.

**Comment by masewo** [comment]
> Also occurred to me as well. After rollback I was able to make version 2.67.1 work by re-applying the following migration step manually: https://github.com/zitadel/zitadel/blob/v2.67.1/cmd/setup/40/postgres/02_func.sql

Did you make it worker with later versions with this? I got the same errors after applying this sql and trying to upgrade to `v2.67.2`.

**Comment by cr1cr1** [comment]
Since [02_func.sql is unchanged](https://github.com/zitadel/zitadel/compare/v2.67.1...v2.67.4/cmd/setup/40/postgres/02_func.sql) since `v2.66.x`, I just ignored the setup error when deploying `v2.67.4` and seems to work just fine.

**Comment by masewo** [comment]
> Since [02_func.sql is unchanged](https://github.com/zitadel/zitadel/compare/v2.67.1...v2.67.4/cmd/setup/40/postgres/02_func.sql) since `v2.66.x`, I just ignored the setup error when deploying `v2.67.4` and seems to work just fine.

Here the application does not come up and putting every 5 seconds an error in the log that the migration is still ongoing.

**Comment by cr1cr1** [comment]
Yeah, I have manually deleted from the database eventstore the entry and manually loaded `02_func.sql`

Make a backup first!

```sql
SELECT e.* FROM eventstore.events2 AS e
WHERE aggregate_type  = 'system'
ORDER BY e.created_at DESC
```

If the newest record has `event_type=system.migration.started`, delete it.

**Comment by cr1cr1** [comment]
Doing some more digging, there is a discrepancy between the enventstore functions in the sql file that is loaded at setup and the actual code of zitadel. Starting with 

> Since [02_func.sql is unchanged](https://github.com/zitadel/zitadel/compare/v2.67.1...v2.67.4/cmd/setup/40/postgres/02_func.sql) since `v2.66.x`, I just ignored the setup error when deploying `v2.67.4` and seems to work just fine.

This is wrong, since github tricked me into displaying a particular file, but it was not. The actual diff is here.
https://github.com/zitadel/zitadel/compare/v2.67.1...v2.67.4/

**Comment by masewo** [comment]
Weird enough that since I restored from my backup and went back to version `v2.67.1` the `pg_wal` folder of my postgres is escalating and consuming every hour 1 GB disk storage more. Any hints what could go wrong there now?

**Comment by muhlemmer** [comment]
@CMiksche

> 1. Have an older version of Zitadel - e.g. 2.67.1 with PostgreSQL
> 2. Upgrade to 2.67.2
> 3. Migration will hang
> 4. Login will not be possible because of the eventstore mismatch

I can't reproduce locally. Any information why the migration was hanging? Any long-running transactions? Any info on (dead)locks from PostgreSQL? Might be the function is used in running transactions if the system has a lot of traffic, which might it make impossible for the migration to continue.

I have double-checked the the function signature. It never changed. That means it should still work in the same queries, regardless of version:

<details>

**40_init_push_func**

```sql
CREATE OR REPLACE FUNCTION eventstore.commands_to_events(commands eventstore.command[])
    RETURNS SETOF eventstore.events2

CREATE OR REPLACE FUNCTION eventstore.push(commands eventstore.command[])
   RETURNS SETOF eventstore.events2
```

**40_init_push_func_v2**

```sql
CREATE OR REPLACE FUNCTION eventstore.commands_to_events(commands eventstore.command[])
    RETURNS SETOF eventstore.events2

CREATE OR REPLACE FUNCTION eventstore.push(commands eventstore.command[])
    RETURNS SETOF eventstore.events2

```

**40_init_push_func_v3**

```sql
CREATE OR REPLACE FUNCTION eventstore.latest_aggregate_state(
    instance_id TEXT
    , aggregate_type TEXT
    , aggregate_id TEXT
    
    , sequence OUT BIGINT
    , owner OUT TEXT
)

CREATE OR REPLACE FUNCTION eventstore.commands_to_events(commands eventstore.command[])
    RETURNS SETOF eventstore.events2 

CREATE OR REPLACE FUNCTION eventstore.push(commands eventstore.command[])     
    RETURNS SETOF eventstore.events2
```

**40_init_push_func_v4**

```sql
CREATE OR REPLACE FUNCTION eventstore.latest_aggregate_state(
    instance_id TEXT
    , aggregate_type TEXT
    , aggregate_id TEXT
    
    , sequence OUT BIGINT
    , owner OUT TEXT
)

CREATE OR REPLACE FUNCTION eventstore.commands_to_events(commands eventstore.command[])
    RETURNS SETOF eventstore.events2

CREATE OR REPLACE FUNCTION eventstore.push(commands eventstore.command[])
    RETURNS SETOF eventstore.events2
```

</details>

The [select query](https://github.com/zitadel/zitadel/blame/main/internal/eventstore/v3/push.go#L91) executing the functions is unchanged over versions, so that can't be the culprit either.

**Comment by muhlemmer** [comment]
@cr1cr1 

> https://github.com/zitadel/zitadel/compare/v2.67.1...v2.67.4/#diff-0f440685a557309928da8b7a3a20abfef04520c18de64ef88091f4b7cf327b33

The linked diff is for cockroachDB, this issue was reported for PostgreSQL. For clarity. Which are you using?

**Comment by muhlemmer** [comment]
> Weird enough that since I restored from my backup and went back to version `v2.67.1` the `pg_wal` folder of my postgres is escalating and consuming every hour 1 GB disk storage more. Any hints what could go wrong there now?

@masewo  Sounds like a lot of events are written or something got stuck on a loop. Check the zitadel logs or database logs and see what's happening. For now I'm going to consider this a seperate problem and please open a separate issue if it persists.

**Comment by muhlemmer** [comment]
For all the others posting they are affected as well, please paste the logs of the setup job. The OP said he lost the logs and no one is providing them instead. That makes it impossible for us to know what's happening.

**Comment by ansarhun** [comment]
@muhlemmer I created a DB dump from the psql server (using v2.67.1), and started up the docker-compose setup with the data imported from the live system, when I start the `v2.67.1` version it starts up fine but when switching to `v2.67.2` it will print out:
```
2025-01-23 19:07:51 time="2025-01-23T18:07:51Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:101"
2025-01-23 19:07:51 time="2025-01-23T18:07:51Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
2025-01-23 19:07:51 time="2025-01-23T18:07:51Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v2
2025-01-23 19:07:51 time="2025-01-23T18:07:51Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:07:57 time="2025-01-23T18:07:57Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:02 time="2025-01-23T18:08:02Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:07 time="2025-01-23T18:08:07Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:12 time="2025-01-23T18:08:12Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:17 time="2025-01-23T18:08:17Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:22 time="2025-01-23T18:08:22Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:27 time="2025-01-23T18:08:27Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:32 time="2025-01-23T18:08:32Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:37 time="2025-01-23T18:08:37Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:42 time="2025-01-23T18:08:42Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
2025-01-23 19:08:47 time="2025-01-23T18:08:47Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v2
```

**Comment by cr1cr1** [comment]
1. v2.67.1 -> v2.67.4

```properties
time="2025-01-23T18:21:10Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:101"
time="2025-01-23T18:21:10Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-01-23T18:21:10Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-01-23T18:21:10Z" level=warning msg="add unique constraint failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v3/unique_constraints.go:78" error="ERROR: duplicate key value violates unique constraint \"unique_constraints_pkey\" (SQLSTATE 23505)"
time="2025-01-23T18:21:10Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:269" error="ID=V3-DKcYh Message=Errors.Step.Started.AlreadyExists Parent=(ERROR: duplicate key value violates unique constraint \"unique_constraints_pkey\" (SQLSTATE 23505))" name=40_init_push_func_v4
```

2. `zitadel setup cleanup`

```properties
time="2025-01-23T18:30:39Z" level=info msg="cleanup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:33"
time="2025-01-23T18:30:39Z" level=info msg="there is no stuck migration please run `zitadel setup`" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:48"
```

3. Retrying the upgrade, seems to be stuck in the same place for Message

```properties
time="2025-01-23T18:33:19Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:101"
time="2025-01-23T18:33:19Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-01-23T18:33:19Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-01-23T18:33:19Z" level=warning msg="add unique constraint failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v3/unique_constraints.go:78" error="ERROR: duplicate key value violates unique constraint \"unique_constraints_pkey\" (SQLSTATE 23505)"
time="2025-01-23T18:33:19Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:269" error="ID=V3-DKcYh Message=Errors.Step.Started.AlreadyExists Parent=(ERROR: duplicate key value violates unique constraint \"unique_constraints_pkey\" (SQLSTATE 23505))" name=40_init_push_func_v4
```

4. Had a stuck record, deleted it

|unique_type      |unique_field         |
|-----------------|---------------------|
|migration_started|40_init_push_func_v4 |

5. Retrying the upgrade

```properties
time="2025-01-23T18:36:58Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:101"
time="2025-01-23T18:36:58Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-01-23T18:36:58Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-01-23T18:36:58Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v4
```

6. `zitadel setup cleanup`, again

```properties
time="2025-01-23T18:38:49Z" level=info msg="cleanup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:33"
time="2025-01-23T18:38:49Z" level=info msg="cleanup migration" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:52" name=40_init_push_func_v4
time="2025-01-23T18:38:49Z" level=fatal msg="cleanup migration failed please retry" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:55" error="ERROR: structure of query does not match function result type (SQLSTATE 42804)"
```

**Comment by draeron** [comment]
if it can be of any help, i'm running single cockroachdb v23.2.9 and I get the same error so I don't think this is related to the database engine.

```40_init_push_func 40_init_push_func.sql: ERROR: unknown function: eventstore.commands_to_events() (SQLSTATE 42883)```

**Comment by muhlemmer** [comment]
> if it can be of any help, i'm running single cockroachdb v23.2.9 and I get the same error when going over v2.65.5 so I don't think this is related to the database engine.
> 
> `40_init_push_func 40_init_push_func.sql: ERROR: unknown function: eventstore.commands_to_events() (SQLSTATE 42883)`

@draeron your comment does not make sense to me.

1. Not the same error. OP reported `SQLSTATE 42804`.
2. v2.65.5 doesn't have the push function migration yet. First version is v2.66.0

**Comment by cr1cr1** [comment]
Using container tag [c300270dd1b1b3d6fc08d4add89ebb3aa51ef28d](https://github.com/zitadel/zitadel/pkgs/container/zitadel/344980917?tag=c300270dd1b1b3d6fc08d4add89ebb3aa51ef28d)

1. Setup was stuck because of existing db record:

```properties
time="2025-01-30T07:49:49Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:103"
time="2025-01-30T07:49:49Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-01-30T07:49:49Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-01-30T07:49:49Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:130" migration step=40_init_push_func_v4
```

2. Run `setup cleanup`

```properties
time="2025-01-30T08:14:09Z" level=info msg="cleanup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:33"
time="2025-01-30T08:14:10Z" level=info msg="cleanup migration" caller="/home/runner/work/zitadel/zitadel/cmd/setup/cleanup.go:52" name=40_init_push_func_v4
```

3. Run normal setup again:

```properties
time="2025-01-30T08:16:32Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:103"
time="2025-01-30T08:16:32Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-01-30T08:16:32Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-01-30T08:16:32Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=40_init_push_func_v4
time="2025-01-30T08:16:32Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/40.go:41" file=01_type.sql migration=40_init_push_func_v4
time="2025-01-30T08:16:32Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/40.go:41" file=02_func.sql migration=40_init_push_func_v4
time="2025-01-30T08:16:32Z" level=error msg="migration finish failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:71" error="ERROR: structure of query does not match function result type (SQLSTATE 42804)" name=40_init_push_func_v4
time="2025-01-30T08:16:32Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:287" code=42804 detail="Returned type integer does not match expected type bigint in column 12." error="ERROR: structure of query does not match function result type (SQLSTATE 42804)" hint= message="structure of query does not match function result type" name=40_init_push_func_v4 severity=ERROR
```

Functions signatures in my database:

```sql
CREATE OR REPLACE FUNCTION eventstore.commands_to_events(commands eventstore.command[])
 RETURNS SETOF eventstore.events2
 LANGUAGE plpgsql
 STABLE PARALLEL SAFE ROWS 10
AS $function$
...
```

```sql
CREATE OR REPLACE FUNCTION eventstore.latest_aggregate_state(instance_id text, aggregate_type text, aggregate_id text, OUT sequence bigint, OUT owner text)
 RETURNS record
 LANGUAGE plpgsql
 STABLE PARALLEL SAFE
AS $function$
...
```

```sql
CREATE OR REPLACE FUNCTION eventstore.push(commands eventstore.command[])
 RETURNS SETOF eventstore.events2
 LANGUAGE sql
AS $function$
...
```

**Comment by muhlemmer** [comment]
This column in `eventstore.events2` seems to be the culprit:

```
in_tx_order int8 NOT NULL,
```

When the events2 table is newly created, it is defined as `INTEGER`. However, when the "upgrade"  was used from the older events table, the `event_sequence` column is used to populate `in_tx_order` and that one was a `BIGINT` (`int8`) type.

https://github.com/zitadel/zitadel/blob/c300270dd1b1b3d6fc08d4add89ebb3aa51ef28d/cmd/setup/14/postgres/02_create_and_fill_events2.sql#L1-L31

For those cases we will need to do an `ALTER TABLE` to change the column type. This will result in a full table lock on the events table for the duration of that migration and might impact productive systems with a large eventstore.

I'll try to propose a fix today and will review it with my colleagues.

**Comment by muhlemmer** [comment]
@draeron This bug should't affect CockroachDB. For them an [`INT`](https://www.cockroachlabs.com/docs/v24.3/int) is the same thing as a `BIGINT` and therefore there can't be a type mismatch as described in my [previous comment](https://github.com/zitadel/zitadel/issues/9180#issuecomment-2630438883). I am mostly sure this bug only affect PostgreSQL deployments.

**Comment by cr1cr1** [comment]
Manual: `ALTER TABLE eventstore.events2 ALTER COLUMN in_tx_order TYPE integer USING in_tx_order::integer;`

1. Bump tag to `v2.67.5`: success
2. Bump tag to `v2.68.1`: setup failed - jumped too close to the sun?

```properties
time="2025-02-03T17:25:36Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:100"
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=01_tables
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=02_assets
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=28_add_search_table
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=31_add_aggregate_index_to_fields
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=03_default_instance
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=05_last_failed
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=06_resource_owner_columns
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=07_logstore
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=08_auth_token_indexes
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=12_auth_users_otp_columns
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=13_fix_quota_constraints
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=15_current_projection_state
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=16_unique_constraint_lower
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=17_add_offset_col_to_current_states
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=19_add_current_sequences_index
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=20_add_by_user_index_on_session
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=22_active_instance_events_index
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=23_correct_global_unique_constraints
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=24_add_actor_col_to_auth_tokens
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=26_auth_users3
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=29_init_fields_for_project_grant
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=30_fill_fields_for_org_domain_verified
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=34_add_cache_schema
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=35_add_position_to_index_es_wm
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=36_fill_v3_milestones
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=38_back_channel_logout_notification_start_
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=44_replace_current_sequences_index
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=43_correct_project_owners
time="2025-02-03T17:25:36Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=01-role_permissions_view.sql migration=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=02-instance_orgs_view.sql migration=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=03-instance_members_view.sql migration=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=04-org_members_view.sql migration=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=05-project_members_view.sql migration=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=06-permitted_orgs_function.sql migration=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="46_init_permission_functions 06-permitted_orgs_function.sql: ERROR: subquery in FROM must have an alias (SQLSTATE 42601)" name=46_init_permission_functions
time="2025-02-03T17:25:36Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:274" error="46_init_permission_functions 06-permitted_orgs_function.sql: ERROR: subquery in FROM must have an alias (SQLSTATE 42601)" name=46_init_permission_functions
```

3. Bump tag lower to `v2.68.0`: success
4. Again, bump tag to `v2.68.1`: success. I was under the wrong impression I can jump to whatever version, and migration will take care of thins, as it is always additive. Not so, upgrading seems to be safest when done incrementally.
5. Felt arrogant, so I bumped to `v2.69.0`: success

So, I confirm altering the column data type was the fix. Thank you @muhlemmer!

**Comment by muhlemmer** [comment]
Thanks for the confirmation @cr1cr1.

> I was under the wrong impression I can jump to whatever version, and migration will take care of thins, as it is always additive

You impression is right and that is how it _should_ work. I'll double check what's happening with 2.68.1.

> Consider permanently leave the detail field in error messages for future potential issues?

Yes, my PR includes the details.

For now I don't dare to merge my PR yet more details here: https://github.com/zitadel/zitadel/pull/9294#issuecomment-2631961913

**Comment by zapling** [comment]
Is the manual fix described in https://github.com/zitadel/zitadel/issues/9180#issuecomment-2631647605 still necessary, or was this resolved in a newer release?

**Comment by chris-1o** [comment]
All releases that have `closes #9180` in the changelog (including 2.70.0) have the bugfix: https://github.com/zitadel/zitadel/releases

I was able to do a successful upgrade today! Thank you for the fix.

**Comment by JesperWe** [comment]
@muhlemmer  

I am still unable to move passed this issue. 

I am running on v2.65.5 and my table looks like this:

```sql
CREATE TABLE eventstore.events2 (
	instance_id text NOT NULL,
	aggregate_type text NOT NULL,
	aggregate_id text NOT NULL,
	event_type text NOT NULL,
	"sequence" int8 NOT NULL,
	revision int2 NOT NULL,
	created_at timestamptz NOT NULL,
	payload jsonb NULL,
	creator text NOT NULL,
	"owner" text NOT NULL,
	"position" numeric NOT NULL,
	in_tx_order int4 NOT NULL,
	CONSTRAINT events2_pkey PRIMARY KEY (instance_id, aggregate_type, aggregate_id, sequence)
);
```

Upgrading to for example v2.69.3, which has "Closes #9180" in the release notes, still fails with

```
[2025-02-21 19:04:41]
level=fatal msg="migration failed" 
caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:292" 
code=42804 
detail="Returned type double precision does not match expected type numeric in column 11." 
error="ERROR: structure of query does not match function result type (SQLSTATE 42804)" 
hint= message="structure of query does not match function result type" 
name=40_init_push_func_v4 severity=ERROR
```

**Comment by muhlemmer** [comment]
@JesperWe I think that is a similar, but different problem.

> Returned type double precision does not match expected type numeric in column 11.

That is a type mis-match of the `position` column. We once had migration of `double` -> `numeric` in [v2.63.0-rc.1](https://github.com/zitadel/zitadel/releases/tag/v2.63.0-rc.1). But after we discovered this was creating some issues, we [reverted](https://github.com/zitadel/zitadel/pull/8679) this change before the stable release [v2.63.0](https://github.com/zitadel/zitadel/releases/tag/v2.63.0).

Did you run that RC? In that case you will have to make sure you fix the related column types manually. I wouldn't be able to tell you what the impact would be on large datasets in production.

**Comment by JesperWe** [comment]
@muhlemmer No, I am 100% sure none of the systems have run any RC version. I have a number of them, all have `position` as `numeric`, even those that are on v2.61.2.

**Comment by muhlemmer** [comment]
Can you please open a new bug for this so we can investigate this further? CC @adlerhurst

**Comment by JesperWe** [comment]
Sure! https://github.com/zitadel/zitadel/issues/9407
