### ISSUE TITLE
[Bug]: Potential Race Condition - flaky error from /oauth/v2/token

### ISSUE THREAD

**Issue by BillyBolton** [zitadel/zitadel#9918]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.71.6

### Database

PostgreSQL

### Database Version

16.3

### Describe the problem caused by this bug

Zitadel Go SDK Version :
- github.com/zitadel/oidc/v3 v3.36.1
- github.com/zitadel/zitadel-go/v3 v3.5.0

I am finding that the `/oauth/v2/token endpoint` is returning a flaky error that to me suggests a race condition.

```bash
time=2025-05-14T15:27:24.757Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
```

The Discord discussion [here](https://discord.com/channels/927474939156643850/1354307516627947530/1354409568364527656) mentions the same error code `ID=QUERY-Tha6f`, however because my issue is flaky, I don't believe it is the same problem as what that user is reporting.

I have already attempted getting support from Discord [here](https://discord.com/channels/927474939156643850/1372242447668875439/1372242447668875439). There are more details in this Github issue, however.

This issue is flaky in various environments. For example, it is not reproduced locally on my machine but it will reproduce in CI/CD environments.

### To reproduce

With the Zitadel GO SDK:

1. Add a machine user
2.  Get machine user by name
3.  Add personal access token with machine user id and a timestamp long exceeding the test, (ie. `&timestamppb.Timestamp{Seconds: time.Now().Add(time.Minute*10).UnixMilli() / 1000}`)
4.  Add machine key with machine user id and a timestamp long exceeding the test, (ie. `&timestamppb.Timestamp{Seconds: time.Now().Add(time.Minute*10).UnixMilli() / 1000}`)
5.  Unmarshal key details to obtain secret value
6.  Create user access token by:
   a.  Create JWT token with an expiration long exceeding the test (ie. `time.Now().Add(time.Hour).Unix()`)
   b. Sign the JWT with your private key
   c. Send signed JWT string to `/oauth/v2/token` endpoint with the following payload values:

```go
func getAccessToken(projectId, signedString string) (string, error) {

	// TODO: Refactor getAccessToken to use zitadel client

	payload := url.Values{}
	payload.Set("grant_type", "urn:ietf:params:oauth:grant-type:jwt-bearer")
	payload.Set("assertion", signedString)
	payload.Set("scope", fmt.Sprintf("openid profile email urn:zitadel:iam:org:project:id:%s:aud", projectId))

	const tokenUri = "%s/oauth/v2/token"
	request, err := http.NewRequest(http.MethodPost, fmt.Sprintf(tokenUri, zitadelBaseUrl), strings.NewReader(payload.Encode()))
	if err != nil {
		return "", err
	}
	request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	request.Header.Add("Content-Length", strconv.Itoa(len(payload.Encode())))
	response, err := client.Do(request)
	if err != nil {
		return "", err
	}
	defer response.Body.Close()
	data, _ := io.ReadAll(response.Body)
	if response.StatusCode != http.StatusOK {
		return "", fmt.Errorf("unexpected response (code: %d): %s", response.StatusCode, string(data))
	}
	var result struct {
		AccessToken string `json:"access_token"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return "", err
	}
	return result.AccessToken, nil
}
```
7. Assert no error occurred

### Expected behavior

The error does not occur consistently (not flaky).

### Operating System

OS: Ubuntu:22.04

**Comment by Fuchsoria** [comment]
Selfhosted version 3.0.4 has similar problem, after signout I see endless refresh with 
Request URL
/oauth/v2/token
Request Method
POST
Status Code
400 Bad Request

{
  "error": "invalid_request",
  "error_description": "Errors.User.NotActive"
}

**Comment by elinashoko** [comment]
Thanks for flagging @BillyBolton, we will look into this. 

cc @adlerhurst

**Comment by adlerhurst** [comment]
Hi there I'm quite sure this issue got fixed in this release: https://github.com/zitadel/zitadel/releases/tag/v2.71.11

can you upgrade to v2.71.11 or higher?

**Comment by BillyBolton** [comment]
Hi @adlerhurst, thanks for checking.

I will check on my side and get back to you sometime next week.

**Comment by BillyBolton** [comment]
Note: since initially reporting this issue, we have migrated to v2.71.10 where the issue still occurred last time I checked.

I could not reproduce the issue using image `ghcr.io/zitadel/zitadel:v2.71.12-debug` however. Therefore, I will trust that this was fixed on `2.71.11` as you say @adlerhurst . Can you point me to the line in the release notes that I can help trace this in case it comes up again, (although doubtful)?

**Comment by sandeep1699** [comment]
@adlerhurst, @BillyBolton Is there any workaround for this issue?

**Comment by BillyBolton** [comment]
@adlerhurst We're seeing this present itself in some of our more rigorous tests, both with the original 2.71.10 I had reported, and today's latest `ghcr.io/zitadel/zitadel:v2.71.19-debug` and `ghcr.io/zitadel/zitadel:v4.6.6-debug`:

```bash
time="2025-11-12T17:31:09Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="https://mydomain:8080" grpcStatus=0 httpStatus=200 instance=346403127538221065 isSystemUser=false method=/zitadel.management.v1.ManagementService/ListUserGrants org=346403633941708809 path= requestMethod= trigger=resourceAPI user=346403127538810889
time=2025-11-12T17:31:10.068Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.086Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.109Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.128Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.149Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.168Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.189Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.207Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.227Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time=2025-11-12T17:31:10.246Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
time="2025-11-12T17:31:10Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:303" error="ID=APP-ASdgg Message=invalid token"
```

Note: Again, the tests that are failing due to this issue pass locally but not in our CI/CD, making me think there is something flaky happening under the hood.

Any updates on this?

Also seems related to this issue somehow: [[Bug]: Public keys passed to add machine key are not stored in the database](https://github.com/zitadel/zitadel/issues/7948) @muhlemmer

**Comment by cloudymax** [comment]
We are seeing this as well on v2.67.2

```console
[14:32:42] DEBUG    check_api_health(): checking if api is up by querying the healthz endpoint, https://iam.website.com/management/v1/, using verify=True
zitadel_api.py:61 INFO      check_api_health(): Zitadel API is up now :)
zitadel_api.py:73 INFO      generate_token(): Creating a jwt so we can request an Oauth token from zitadel
zitadel_api.py:101 INFO     generate_token(): Requesting an API token from zitadel...
zitadel_api.py:114 DEBUG    generate_token(): res is <Response [500]>
zitadel_api.py:126 DEBUG    generate_token(): json_blob is {'error': 'server_error', 'error_description': 'Errors.Internal'}
zitadel_api.py:131 DEBUG    generate_token(): there was an error: 'access_token'
zitadel_api.py:134 DEBUG    generate_token(): json_blob is <bound method Response.json of <Response [500]>>
```

```console
time="2025-12-25T13:32:08Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:584"
time="2025-12-25T13:32:42Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="https://iam.website.com" grpcStatus=0 httpStatus=200 instance=352611323751695074 isSystemUser=false method=/zitadel.management.v1.ManagementService/Healthz org= path=/healthz requestMethod=GET trigger=resourceAPI user=
time=2025-12-25T13:32:42.267Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
```

**Comment by muhlemmer** [comment]
Hi we no longer provide fixes for any v2.xx, please upgrade to a newer version and see if the issue still exists. I recommend at least v4.

**Comment by BillyBolton** [comment]
I understand v2.x isn't supported anymore, but was there any changes that would have addressed this since then? Or are we just waiting for deprecation cycles and asking users to retest with every major release?

**Comment by muhlemmer** [comment]
We had several fixes wrt flaky in projections since this issue was posted. Also, in order to find bugs we need to be able to run and reproduce. As we no longer support v2 we won't be able to reproduce it for that specific version.

**Comment by BillyBolton** [comment]
I suppose we can close this issue then.
